import type { Market } from '@/types'

export const mockMarkets: Market[] = [
  {
    slug: 'monoclonal-antibodies',
    title: 'Monoclonal Antibodies',
    industry: 'Biotechnology',
    subIndustry: 'Monoclonal Antibodies',
    region: 'global',
    type: 'Report',
    description: 'The global monoclonal antibodies market is witnessing significant growth driven by rising prevalence of chronic diseases and cancer. Advanced biologics manufacturing capabilities are further supporting market expansion.',
    revenue: 211.4,
    forecast: 498.7,
    cagr: 11.2,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 115.2 }, { year: 2019, value: 130.8 }, { year: 2020, value: 148.1 },
      { year: 2021, value: 168.9 }, { year: 2022, value: 192.3 }, { year: 2023, value: 211.4 },
      { year: 2024, value: 235.0 }, { year: 2025, value: 261.8 }, { year: 2026, value: 291.5 },
      { year: 2027, value: 324.8 }, { year: 2028, value: 361.6 }, { year: 2029, value: 428.2 },
      { year: 2030, value: 498.7 },
    ],
    segments: ['Source Type', 'Production Type', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Roche', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'AbbVie', employees: '50,000+', hq: 'North Chicago, USA', website: 'abbvie.com' },
      { name: 'Regeneron Pharmaceuticals', employees: '11,000+', hq: 'Tarrytown, USA', website: 'regeneron.com' },
      { name: 'Bristol-Myers Squibb', employees: '32,200+', hq: 'New York, USA', website: 'bms.com' },
      { name: 'Johnson & Johnson', employees: '152,000+', hq: 'New Brunswick, USA', website: 'jnj.com' },
      { name: 'Novartis', employees: '108,000+', hq: 'Basel, Switzerland', website: 'novartis.com' },
      { name: 'Amgen', employees: '24,000+', hq: 'Thousand Oaks, USA', website: 'amgen.com' },
      { name: 'Pfizer', employees: '83,000+', hq: 'New York, USA', website: 'pfizer.com' },
    ],
    highlights: [
      'Cancer treatment remains the largest application segment, accounting for 45% of total market revenue',
      'Humanized monoclonal antibodies dominate with 65% market share due to reduced immunogenicity',
      'North America leads the global market, contributing over 42% of total revenues in 2023',
      'Biosimilar development is gaining traction as key patents expire, creating cost-effective alternatives',
      'Asia Pacific is projected to be the fastest-growing region with a CAGR of 14.2% through 2030',
    ],
    relatedMarkets: [
      'North America Monoclonal Antibodies Market', 'Europe Monoclonal Antibodies Market',
      'Bispecific Antibodies Market', 'Antibody Drug Conjugates Market',
      'Biosimilars Market', 'Cancer Immunotherapy Market',
    ],
  },
  {
    slug: 'electric-vehicles',
    title: 'Electric Vehicles',
    industry: 'Automotive & Transportation',
    subIndustry: 'Electric Vehicles',
    region: 'global',
    type: 'Report',
    description: 'The global electric vehicle market continues to accelerate as government mandates, falling battery costs, and expanding charging infrastructure drive mass adoption across passenger and commercial segments.',
    revenue: 388.1,
    forecast: 951.9,
    cagr: 13.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 102.3 }, { year: 2019, value: 126.7 }, { year: 2020, value: 143.9 },
      { year: 2021, value: 198.4 }, { year: 2022, value: 302.1 }, { year: 2023, value: 388.1 },
      { year: 2024, value: 445.2 }, { year: 2025, value: 523.8 }, { year: 2026, value: 621.0 },
      { year: 2027, value: 728.4 }, { year: 2028, value: 810.3 }, { year: 2029, value: 888.7 },
      { year: 2030, value: 951.9 },
    ],
    segments: ['Vehicle Type', 'Propulsion Type', 'Vehicle Class', 'End Use', 'Region'],
    companies: [
      { name: 'Tesla', employees: '127,855', hq: 'Austin, USA', website: 'tesla.com' },
      { name: 'BYD', employees: '570,000+', hq: 'Shenzhen, China', website: 'bydglobal.com' },
      { name: 'Volkswagen Group', employees: '684,000+', hq: 'Wolfsburg, Germany', website: 'volkswagen-group.com' },
      { name: 'General Motors', employees: '163,000', hq: 'Detroit, USA', website: 'gm.com' },
    ],
    highlights: [
      'Battery Electric Vehicles (BEVs) account for 71% of market share in 2023',
      'China dominates global EV adoption with 59% of new EV registrations',
      'Average EV battery cost has fallen 89% over the past decade to below $120/kWh',
      'Government incentives and stricter emission norms continue to accelerate adoption',
    ],
    relatedMarkets: [
      'EV Battery Market', 'EV Charging Infrastructure Market',
      'Autonomous Vehicle Market', 'Battery Management System Market',
    ],
  },
  {
    slug: 'solar-energy',
    title: 'Solar Energy',
    industry: 'Energy & Power',
    subIndustry: 'Solar Energy',
    region: 'global',
    type: 'Report',
    description: 'The global solar energy market is experiencing unprecedented growth as declining photovoltaic panel costs and strong policy support make solar one of the cheapest forms of new electricity generation.',
    revenue: 223.8,
    forecast: 612.4,
    cagr: 15.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 89.4 }, { year: 2019, value: 108.1 }, { year: 2020, value: 121.7 },
      { year: 2021, value: 155.3 }, { year: 2022, value: 194.2 }, { year: 2023, value: 223.8 },
      { year: 2024, value: 263.5 }, { year: 2025, value: 314.2 }, { year: 2026, value: 378.9 },
      { year: 2027, value: 449.3 }, { year: 2028, value: 512.8 }, { year: 2029, value: 563.7 },
      { year: 2030, value: 612.4 },
    ],
    segments: ['Technology', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'LONGi Green Energy', employees: '80,000+', hq: "Xi'an, China", website: 'longi.com' },
      { name: 'First Solar', employees: '9,800+', hq: 'Tempe, USA', website: 'firstsolar.com' },
      { name: 'Sunrun', employees: '15,000+', hq: 'San Francisco, USA', website: 'sunrun.com' },
    ],
    highlights: [
      'Utility-scale solar installations represent 65% of total capacity additions globally',
      'Solar panel costs have declined 90% over the last decade, now below $0.20/W',
      'India and China combined account for 45% of new solar capacity additions',
      'Floating solar installations grew 30% YoY driven by land scarcity concerns',
    ],
    relatedMarkets: ['Solar Panel Market', 'Solar Inverter Market', 'Energy Storage Market', 'Wind Energy Market'],
  },
  {
    slug: 'digital-health',
    title: 'Digital Health',
    industry: 'Healthcare',
    subIndustry: 'Digital Health',
    region: 'global',
    type: 'Report',
    description: 'The digital health market encompasses telemedicine, health IT, wearable devices, and AI-powered diagnostics. Increasing smartphone penetration and post-pandemic behavioral shifts are sustaining robust growth.',
    revenue: 211.0,
    forecast: 809.2,
    cagr: 21.2,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 86.4 }, { year: 2019, value: 101.2 }, { year: 2020, value: 152.8 },
      { year: 2021, value: 178.3 }, { year: 2022, value: 196.4 }, { year: 2023, value: 211.0 },
      { year: 2024, value: 268.4 }, { year: 2025, value: 341.7 }, { year: 2026, value: 428.3 },
      { year: 2027, value: 531.2 }, { year: 2028, value: 634.9 }, { year: 2029, value: 723.8 },
      { year: 2030, value: 809.2 },
    ],
    segments: ['Component', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Teladoc Health', employees: '14,000+', hq: 'Purchase, USA', website: 'teladochealth.com' },
      { name: 'Philips Healthcare', employees: '77,000+', hq: 'Amsterdam, Netherlands', website: 'philips.com' },
      { name: 'Epic Systems', employees: '10,000+', hq: 'Verona, USA', website: 'epic.com' },
    ],
    highlights: [
      'Telehealth segment led the market with 28% revenue share in 2023',
      'AI-powered diagnostics are projected to grow at 28% CAGR through 2030',
      'Remote patient monitoring adoption doubled post-COVID-19',
    ],
    relatedMarkets: ['Telehealth Market', 'Health IT Market', 'Wearable Medical Devices Market', 'AI in Healthcare Market'],
  },
  {
    slug: 'gene-therapy',
    title: 'Gene Therapy',
    industry: 'Biotechnology',
    subIndustry: 'Gene Therapy',
    region: 'global',
    type: 'Report',
    description: 'Gene therapy is revolutionizing treatment of genetic disorders, rare diseases, and oncology. Advances in viral vector manufacturing and CRISPR technologies are accelerating clinical pipeline development.',
    revenue: 6.8,
    forecast: 38.2,
    cagr: 28.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 1.2 }, { year: 2019, value: 1.9 }, { year: 2020, value: 2.8 },
      { year: 2021, value: 3.9 }, { year: 2022, value: 5.4 }, { year: 2023, value: 6.8 },
      { year: 2024, value: 9.2 }, { year: 2025, value: 12.4 }, { year: 2026, value: 16.8 },
      { year: 2027, value: 22.1 }, { year: 2028, value: 27.8 }, { year: 2029, value: 32.9 },
      { year: 2030, value: 38.2 },
    ],
    segments: ['Vector Type', 'Disease Indication', 'Delivery Mode', 'End Use', 'Region'],
    companies: [
      { name: 'Novartis', employees: '108,000+', hq: 'Basel, Switzerland', website: 'novartis.com' },
      { name: 'Bluebird Bio', employees: '1,400+', hq: 'Cambridge, USA', website: 'bluebirdbio.com' },
      { name: 'Spark Therapeutics', employees: '750+', hq: 'Philadelphia, USA', website: 'sparktx.com' },
    ],
    highlights: [
      'AAV-based gene therapies dominate the pipeline with over 65% of clinical trials using this vector',
      'Rare genetic disorders represent the largest disease indication segment',
      'CRISPR-based therapies advancing rapidly with first FDA approvals in 2023',
    ],
    relatedMarkets: ['Cell Therapy Market', 'CRISPR Technology Market', 'Rare Disease Treatment Market'],
  },
  {
    slug: 'surgical-robotics',
    title: 'Surgical Robotics',
    industry: 'MedTech',
    subIndustry: 'Surgical Robotics',
    region: 'global',
    type: 'Report',
    description: 'Surgical robotics systems are transforming minimally invasive surgery with enhanced precision and reduced recovery times. Growing surgical volumes and expanding robotic platform capabilities are driving adoption.',
    revenue: 14.7,
    forecast: 45.6,
    cagr: 17.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 5.2 }, { year: 2019, value: 6.4 }, { year: 2020, value: 6.9 },
      { year: 2021, value: 8.7 }, { year: 2022, value: 11.8 }, { year: 2023, value: 14.7 },
      { year: 2024, value: 17.9 }, { year: 2025, value: 21.8 }, { year: 2026, value: 26.4 },
      { year: 2027, value: 31.8 }, { year: 2028, value: 37.2 }, { year: 2029, value: 41.8 },
      { year: 2030, value: 45.6 },
    ],
    segments: ['Product Type', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Intuitive Surgical', employees: '12,000+', hq: 'Sunnyvale, USA', website: 'intuitivesurgical.com' },
      { name: 'Medtronic', employees: '95,000+', hq: 'Dublin, Ireland', website: 'medtronic.com' },
      { name: 'Stryker', employees: '51,000+', hq: 'Kalamazoo, USA', website: 'stryker.com' },
    ],
    highlights: [
      'Da Vinci system by Intuitive Surgical holds ~55% global market share',
      'Orthopaedic robotic surgery growing fastest at 22% CAGR',
      'AI integration enabling real-time surgical guidance and outcome prediction',
    ],
    relatedMarkets: ['Minimally Invasive Surgery Market', 'Orthopedic Implants Market', 'Operating Room Equipment Market'],
  },
  {
    slug: 'molecular-diagnostics',
    title: 'Molecular Diagnostics',
    industry: 'Clinical Diagnostics',
    subIndustry: 'Molecular Diagnostics',
    region: 'global',
    type: 'Databook',
    description: 'Molecular diagnostics leverages DNA, RNA, and protein biomarker detection for infectious disease, oncology, and genetic testing. Post-COVID infrastructure investments are fueling sustained market growth.',
    revenue: 17.8,
    forecast: 42.3,
    cagr: 13.3,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 8.2 }, { year: 2019, value: 9.8 }, { year: 2020, value: 18.6 },
      { year: 2021, value: 22.4 }, { year: 2022, value: 19.1 }, { year: 2023, value: 17.8 },
      { year: 2024, value: 20.2 }, { year: 2025, value: 23.4 }, { year: 2026, value: 27.1 },
      { year: 2027, value: 31.3 }, { year: 2028, value: 35.2 }, { year: 2029, value: 38.9 },
      { year: 2030, value: 42.3 },
    ],
    segments: ['Technology', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'Roche Diagnostics', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'Abbott', employees: '113,000+', hq: 'Abbott Park, USA', website: 'abbott.com' },
      { name: 'Qiagen', employees: '6,200+', hq: 'Hilden, Germany', website: 'qiagen.com' },
    ],
    highlights: [
      'PCR technology remains dominant with 38% revenue share in 2023',
      'NGS-based diagnostics growing at 18% CAGR driven by oncology applications',
      'Point-of-care molecular testing expanding rapidly in low-resource settings',
    ],
    relatedMarkets: ['Point-of-Care Testing Market', 'NGS Market', 'Infectious Disease Diagnostics Market'],
  },
  {
    slug: 'ev-battery',
    title: 'EV Battery',
    industry: 'Automotive & Transportation',
    subIndustry: 'Electric Vehicles',
    region: 'global',
    type: 'Report',
    description: 'The EV battery market is the cornerstone of the electric mobility revolution. Declining lithium-ion costs, solid-state battery development, and gigafactory expansions are reshaping the competitive landscape.',
    revenue: 92.4,
    forecast: 387.3,
    cagr: 22.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 18.2 }, { year: 2019, value: 25.1 }, { year: 2020, value: 32.8 },
      { year: 2021, value: 48.6 }, { year: 2022, value: 72.3 }, { year: 2023, value: 92.4 },
      { year: 2024, value: 122.8 }, { year: 2025, value: 161.4 }, { year: 2026, value: 208.3 },
      { year: 2027, value: 261.7 }, { year: 2028, value: 310.2 }, { year: 2029, value: 352.8 },
      { year: 2030, value: 387.3 },
    ],
    segments: ['Battery Type', 'Vehicle Type', 'Capacity', 'Region'],
    companies: [
      { name: 'CATL', employees: '92,000+', hq: 'Ningde, China', website: 'catl.com' },
      { name: 'LG Energy Solution', employees: '30,000+', hq: 'Seoul, South Korea', website: 'lges.com' },
      { name: 'Panasonic', employees: '240,000+', hq: 'Osaka, Japan', website: 'panasonic.com' },
    ],
    highlights: [
      'CATL holds 37% global EV battery market share in 2023',
      'Solid-state batteries expected to reach commercial scale by 2027',
      'Lithium iron phosphate (LFP) chemistry gaining share due to lower cost',
    ],
    relatedMarkets: ['Electric Vehicles Market', 'Battery Management Systems Market', 'Lithium Mining Market'],
  },
  {
    slug: 'oncology-drugs',
    title: 'Oncology Drugs',
    industry: 'Pharmaceuticals',
    subIndustry: 'Oncology',
    region: 'global',
    type: 'Report',
    description: 'The oncology drugs market remains the largest therapeutic segment in pharmaceuticals. Immunotherapy, targeted therapy, and cell therapy innovations continue to expand treatment options across cancer types.',
    revenue: 248.6,
    forecast: 598.4,
    cagr: 13.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 118.4 }, { year: 2019, value: 138.7 }, { year: 2020, value: 153.2 },
      { year: 2021, value: 178.9 }, { year: 2022, value: 214.3 }, { year: 2023, value: 248.6 },
      { year: 2024, value: 291.2 }, { year: 2025, value: 341.8 }, { year: 2026, value: 398.4 },
      { year: 2027, value: 458.2 }, { year: 2028, value: 518.7 }, { year: 2029, value: 561.3 },
      { year: 2030, value: 598.4 },
    ],
    segments: ['Drug Class', 'Cancer Type', 'Therapy Line', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Roche', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'Bristol-Myers Squibb', employees: '32,200+', hq: 'New York, USA', website: 'bms.com' },
      { name: 'Merck & Co.', employees: '68,000+', hq: 'Rahway, USA', website: 'merck.com' },
      { name: 'AstraZeneca', employees: '83,000+', hq: 'Cambridge, UK', website: 'astrazeneca.com' },
    ],
    highlights: [
      'Checkpoint inhibitors (PD-1/PD-L1) are the largest drug class with 31% revenue share',
      'CAR-T cell therapies gaining traction, with 8 FDA-approved products as of 2024',
      'Lung cancer remains the largest indication driving oncology drug revenue',
    ],
    relatedMarkets: ['Immunotherapy Market', 'CAR-T Cell Therapy Market', 'Cancer Diagnostics Market'],
  },
  {
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    industry: 'Telecom & Technology',
    subIndustry: 'Cybersecurity',
    region: 'global',
    type: 'Report',
    description: 'The global cybersecurity market is driven by escalating ransomware attacks, regulatory compliance requirements, and digital transformation across enterprises. Zero-trust architecture adoption is reshaping enterprise security stacks.',
    revenue: 202.7,
    forecast: 562.7,
    cagr: 15.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 102.1 }, { year: 2019, value: 120.9 }, { year: 2020, value: 137.6 },
      { year: 2021, value: 155.8 }, { year: 2022, value: 180.2 }, { year: 2023, value: 202.7 },
      { year: 2024, value: 241.1 }, { year: 2025, value: 287.3 }, { year: 2026, value: 341.8 },
      { year: 2027, value: 403.2 }, { year: 2028, value: 466.4 }, { year: 2029, value: 517.9 },
      { year: 2030, value: 562.7 },
    ],
    segments: ['Solution', 'Service', 'Deployment', 'Organization Size', 'Vertical', 'Region'],
    companies: [
      { name: 'Palo Alto Networks', employees: '14,000+', hq: 'Santa Clara, USA', website: 'paloaltonetworks.com' },
      { name: 'CrowdStrike', employees: '9,800+', hq: 'Austin, USA', website: 'crowdstrike.com' },
      { name: 'Fortinet', employees: '12,700+', hq: 'Sunnyvale, USA', website: 'fortinet.com' },
      { name: 'Microsoft', employees: '221,000+', hq: 'Redmond, USA', website: 'microsoft.com' },
    ],
    highlights: [
      'Cloud security is the fastest-growing segment at 24% CAGR through 2030',
      'AI-driven threat detection becoming standard in endpoint security platforms',
      'Ransomware attacks increased 73% in 2023, driving enterprise security budgets',
    ],
    relatedMarkets: ['Cloud Security Market', 'Zero Trust Security Market', 'Identity & Access Management Market'],
  },
  {
    slug: 'fintech',
    title: 'Fintech',
    industry: 'Financial Services',
    subIndustry: 'Fintech',
    region: 'global',
    type: 'Report',
    description: 'Fintech is disrupting traditional banking and financial services through digital payments, embedded finance, and AI-driven credit scoring. Emerging markets are particularly driving mobile-first financial inclusion.',
    revenue: 312.4,
    forecast: 1152.1,
    cagr: 20.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 89.3 }, { year: 2019, value: 118.6 }, { year: 2020, value: 148.3 },
      { year: 2021, value: 192.7 }, { year: 2022, value: 258.4 }, { year: 2023, value: 312.4 },
      { year: 2024, value: 388.6 }, { year: 2025, value: 491.3 }, { year: 2026, value: 618.7 },
      { year: 2027, value: 771.4 }, { year: 2028, value: 918.2 }, { year: 2029, value: 1042.8 },
      { year: 2030, value: 1152.1 },
    ],
    segments: ['Service', 'Technology', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Stripe', employees: '8,000+', hq: 'San Francisco, USA', website: 'stripe.com' },
      { name: 'PayPal', employees: '29,900+', hq: 'San Jose, USA', website: 'paypal.com' },
      { name: 'Ant Group', employees: '28,000+', hq: 'Hangzhou, China', website: 'antgroup.com' },
      { name: 'Revolut', employees: '8,000+', hq: 'London, UK', website: 'revolut.com' },
    ],
    highlights: [
      'Digital payments represent 54% of total fintech revenue in 2023',
      'BNPL (Buy Now Pay Later) growing at 26% CAGR as consumer credit shifts',
      'Embedded finance projected to reach $384B by 2030',
    ],
    relatedMarkets: ['Digital Payments Market', 'InsurTech Market', 'RegTech Market', 'Blockchain Market'],
  },
  {
    slug: 'cloud-computing',
    title: 'Cloud Computing',
    industry: 'Telecom & Technology',
    subIndustry: 'Cloud Computing',
    region: 'global',
    type: 'Databook',
    description: 'Cloud computing underpins the digital economy with IaaS, PaaS, and SaaS solutions. Generative AI workloads, hybrid cloud adoption, and edge computing are creating new growth vectors for hyperscalers.',
    revenue: 591.8,
    forecast: 2376.4,
    cagr: 21.9,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 182.3 }, { year: 2019, value: 233.4 }, { year: 2020, value: 312.1 },
      { year: 2021, value: 408.9 }, { year: 2022, value: 501.3 }, { year: 2023, value: 591.8 },
      { year: 2024, value: 742.6 }, { year: 2025, value: 928.4 }, { year: 2026, value: 1148.2 },
      { year: 2027, value: 1412.8 }, { year: 2028, value: 1718.4 }, { year: 2029, value: 2058.7 },
      { year: 2030, value: 2376.4 },
    ],
    segments: ['Service Model', 'Deployment Model', 'Enterprise Size', 'Industry Vertical', 'Region'],
    companies: [
      { name: 'Amazon Web Services', employees: '1,600,000+', hq: 'Seattle, USA', website: 'aws.amazon.com' },
      { name: 'Microsoft Azure', employees: '221,000+', hq: 'Redmond, USA', website: 'azure.microsoft.com' },
      { name: 'Google Cloud', employees: '182,000+', hq: 'Mountain View, USA', website: 'cloud.google.com' },
    ],
    highlights: [
      'AWS, Azure, and Google Cloud collectively hold 66% of global cloud market share',
      'Generative AI infrastructure spending driving 35% increase in cloud capex in 2024',
      'Multi-cloud adoption reaches 87% among enterprise organizations',
    ],
    relatedMarkets: ['AI Infrastructure Market', 'Edge Computing Market', 'Serverless Computing Market'],
  },
  {
    slug: 'pharmaceutical-packaging',
    title: 'Pharmaceutical Packaging',
    industry: 'Packaging',
    subIndustry: 'Flexible Packaging',
    region: 'global',
    type: 'Databook',
    description: 'Pharmaceutical packaging ensures drug safety, compliance, and patient adherence. Growing biologics pipelines requiring specialized cold-chain packaging and rising unit dose demand are key market drivers.',
    revenue: 123.4,
    forecast: 248.7,
    cagr: 10.6,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 71.2 }, { year: 2019, value: 79.4 }, { year: 2020, value: 88.1 },
      { year: 2021, value: 97.8 }, { year: 2022, value: 111.3 }, { year: 2023, value: 123.4 },
      { year: 2024, value: 136.8 }, { year: 2025, value: 151.2 }, { year: 2026, value: 167.4 },
      { year: 2027, value: 185.6 }, { year: 2028, value: 206.3 }, { year: 2029, value: 227.8 },
      { year: 2030, value: 248.7 },
    ],
    segments: ['Material', 'Product Type', 'Drug Type', 'Region'],
    companies: [
      { name: 'Amcor', employees: '44,000+', hq: 'Zurich, Switzerland', website: 'amcor.com' },
      { name: 'Berry Global', employees: '48,000+', hq: 'Evansville, USA', website: 'berryglobal.com' },
      { name: 'Gerresheimer', employees: '11,400+', hq: 'Düsseldorf, Germany', website: 'gerresheimer.com' },
    ],
    highlights: [
      'Blister packaging dominates with 42% revenue share in solid dose pharmaceuticals',
      'Prefillable syringes growing at 12% CAGR driven by biologics administration',
      'Smart packaging with RFID and temperature indicators gaining regulatory traction',
    ],
    relatedMarkets: ['Drug Delivery Systems Market', 'Cold Chain Packaging Market', 'Sustainable Packaging Market'],
  },
  {
    slug: 'ai-in-healthcare',
    title: 'AI in Healthcare',
    industry: 'Healthcare',
    subIndustry: 'Health IT',
    region: 'global',
    type: 'Report',
    description: 'AI in healthcare is transforming diagnostics, drug discovery, clinical operations, and patient engagement. Large language models and multimodal AI are emerging as the next frontier in clinical decision support.',
    revenue: 19.8,
    forecast: 187.9,
    cagr: 37.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 2.1 }, { year: 2019, value: 3.4 }, { year: 2020, value: 5.8 },
      { year: 2021, value: 8.9 }, { year: 2022, value: 13.9 }, { year: 2023, value: 19.8 },
      { year: 2024, value: 30.1 }, { year: 2025, value: 46.2 }, { year: 2026, value: 69.8 },
      { year: 2027, value: 100.4 }, { year: 2028, value: 133.7 }, { year: 2029, value: 162.8 },
      { year: 2030, value: 187.9 },
    ],
    segments: ['Component', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'IBM Watson Health', employees: '350,000+', hq: 'Armonk, USA', website: 'ibm.com' },
      { name: 'Google Health', employees: '182,000+', hq: 'Mountain View, USA', website: 'health.google' },
      { name: 'Tempus AI', employees: '3,000+', hq: 'Chicago, USA', website: 'tempus.com' },
    ],
    highlights: [
      'Medical imaging AI is the largest application segment at 29% revenue share',
      'Drug discovery AI reduces preclinical timelines by up to 40%',
      'NLP-based clinical documentation tools adopted by 62% of US health systems',
    ],
    relatedMarkets: ['Digital Health Market', 'Radiology AI Market', 'AI Drug Discovery Market'],
  },
  {
    slug: 'wind-energy',
    title: 'Wind Energy',
    industry: 'Energy & Power',
    subIndustry: 'Wind Energy',
    region: 'global',
    type: 'Report',
    description: 'Wind energy is a cornerstone of global renewable energy transition. Offshore wind expansion, turbine technology improvements, and favorable policy frameworks are driving capacity additions worldwide.',
    revenue: 108.2,
    forecast: 298.4,
    cagr: 15.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 54.3 }, { year: 2019, value: 63.8 }, { year: 2020, value: 74.1 },
      { year: 2021, value: 84.9 }, { year: 2022, value: 97.4 }, { year: 2023, value: 108.2 },
      { year: 2024, value: 128.7 }, { year: 2025, value: 153.2 }, { year: 2026, value: 182.8 },
      { year: 2027, value: 216.4 }, { year: 2028, value: 251.8 }, { year: 2029, value: 276.2 },
      { year: 2030, value: 298.4 },
    ],
    segments: ['Type', 'Component', 'Location', 'Capacity', 'Region'],
    companies: [
      { name: 'Vestas', employees: '29,000+', hq: 'Aarhus, Denmark', website: 'vestas.com' },
      { name: 'Siemens Gamesa', employees: '27,000+', hq: 'Zamudio, Spain', website: 'siemensgamesa.com' },
      { name: 'GE Vernova', employees: '80,000+', hq: 'Cambridge, USA', website: 'gevernova.com' },
    ],
    highlights: [
      'Offshore wind capacity additions surpassed onshore for first time in Europe in 2023',
      'Floating offshore wind technology unlocking deeper water deployment',
      'China accounts for 60% of global new onshore wind installations',
    ],
    relatedMarkets: ['Solar Energy Market', 'Energy Storage Market', 'Offshore Wind Market'],
  },
  {
    slug: 'point-of-care-testing',
    title: 'Point-of-Care Testing',
    industry: 'Clinical Diagnostics',
    subIndustry: 'Point-of-Care Testing',
    region: 'global',
    type: 'Statistics',
    description: 'Point-of-care testing enables rapid diagnostic results outside traditional laboratory settings. Post-pandemic infrastructure and home testing normalization are creating sustained demand growth.',
    revenue: 48.3,
    forecast: 102.7,
    cagr: 11.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 21.4 }, { year: 2019, value: 25.1 }, { year: 2020, value: 42.8 },
      { year: 2021, value: 51.2 }, { year: 2022, value: 53.4 }, { year: 2023, value: 48.3 },
      { year: 2024, value: 55.1 }, { year: 2025, value: 63.2 }, { year: 2026, value: 72.8 },
      { year: 2027, value: 82.4 }, { year: 2028, value: 90.6 }, { year: 2029, value: 97.4 },
      { year: 2030, value: 102.7 },
    ],
    segments: ['Product', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'Abbott', employees: '113,000+', hq: 'Abbott Park, USA', website: 'abbott.com' },
      { name: 'Roche Diagnostics', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'bioMérieux', employees: '14,200+', hq: 'Marcy-l\'Étoile, France', website: 'biomerieux.com' },
    ],
    highlights: [
      'Infectious disease testing accounts for 42% of POCT revenue in 2023',
      'Home testing kits market growing at 18% CAGR post-COVID normalization',
      'Lateral flow assays remain most widely used POCT format globally',
    ],
    relatedMarkets: ['Molecular Diagnostics Market', 'Immunoassay Market', 'Home Diagnostics Market'],
  },
  {
    slug: 'sports-nutrition',
    title: 'Sports Nutrition',
    industry: 'Nutrition',
    subIndustry: 'Sports Nutrition',
    region: 'global',
    type: 'Databook',
    description: 'The sports nutrition market is expanding beyond athletes to encompass fitness enthusiasts, aging populations, and preventive health consumers. Protein supplements, energy products, and recovery formulations lead demand.',
    revenue: 47.2,
    forecast: 98.4,
    cagr: 11.1,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 26.8 }, { year: 2019, value: 30.2 }, { year: 2020, value: 32.1 },
      { year: 2021, value: 37.4 }, { year: 2022, value: 42.8 }, { year: 2023, value: 47.2 },
      { year: 2024, value: 52.4 }, { year: 2025, value: 58.3 }, { year: 2026, value: 65.4 },
      { year: 2027, value: 73.2 }, { year: 2028, value: 81.8 }, { year: 2029, value: 90.4 },
      { year: 2030, value: 98.4 },
    ],
    segments: ['Product Type', 'Form', 'Distribution Channel', 'Consumer Type', 'Region'],
    companies: [
      { name: 'Glanbia', employees: '6,500+', hq: 'Kilkenny, Ireland', website: 'glanbia.com' },
      { name: 'Abbott Nutrition', employees: '113,000+', hq: 'Abbott Park, USA', website: 'abbott.com' },
      { name: 'PepsiCo', employees: '315,000+', hq: 'Purchase, USA', website: 'pepsico.com' },
    ],
    highlights: [
      'Protein supplements hold largest product share at 38% in 2023',
      'Plant-based protein demand growing at 15% CAGR among fitness consumers',
      'E-commerce channels now represent 35% of sports nutrition sales globally',
    ],
    relatedMarkets: ['Dietary Supplements Market', 'Functional Food Market', 'Probiotic Market'],
  },
  {
    slug: '5g-infrastructure',
    title: '5G Infrastructure',
    industry: 'Telecom & Technology',
    subIndustry: '5G',
    region: 'global',
    type: 'Report',
    description: '5G infrastructure buildout is accelerating across developed and emerging markets, enabling ultra-low latency applications in autonomous vehicles, industrial IoT, and immersive media experiences.',
    revenue: 74.8,
    forecast: 312.4,
    cagr: 22.6,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 4.2 }, { year: 2019, value: 8.9 }, { year: 2020, value: 18.4 },
      { year: 2021, value: 32.1 }, { year: 2022, value: 54.3 }, { year: 2023, value: 74.8 },
      { year: 2024, value: 98.2 }, { year: 2025, value: 132.4 }, { year: 2026, value: 175.8 },
      { year: 2027, value: 219.4 }, { year: 2028, value: 258.7 }, { year: 2029, value: 289.3 },
      { year: 2030, value: 312.4 },
    ],
    segments: ['Component', 'Frequency', 'Network Architecture', 'End User', 'Region'],
    companies: [
      { name: 'Ericsson', employees: '110,000+', hq: 'Stockholm, Sweden', website: 'ericsson.com' },
      { name: 'Nokia', employees: '86,000+', hq: 'Espoo, Finland', website: 'nokia.com' },
      { name: 'Huawei', employees: '207,000+', hq: 'Shenzhen, China', website: 'huawei.com' },
    ],
    highlights: [
      'China leads global 5G base station deployments with 2.3M stations by end-2023',
      'Private 5G networks for industrial IoT growing at 28% CAGR',
      'Open RAN architecture gaining traction among Tier 2 and Tier 3 operators',
    ],
    relatedMarkets: ['IoT Market', 'Network Slicing Market', 'Edge Computing Market'],
  },
  {
    slug: 'dietary-supplements',
    title: 'Dietary Supplements',
    industry: 'Nutrition',
    subIndustry: 'Dietary Supplements',
    region: 'global',
    type: 'Databook',
    description: 'Dietary supplements market spans vitamins, minerals, botanicals, and specialty ingredients. Consumer self-care trends, aging demographics, and preventive healthcare shifts are driving consistent category growth.',
    revenue: 178.8,
    forecast: 381.2,
    cagr: 11.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 96.4 }, { year: 2019, value: 109.3 }, { year: 2020, value: 132.8 },
      { year: 2021, value: 151.9 }, { year: 2022, value: 167.4 }, { year: 2023, value: 178.8 },
      { year: 2024, value: 199.2 }, { year: 2025, value: 222.4 }, { year: 2026, value: 248.3 },
      { year: 2027, value: 278.4 }, { year: 2028, value: 311.8 }, { year: 2029, value: 347.2 },
      { year: 2030, value: 381.2 },
    ],
    segments: ['Product Type', 'Form', 'Application', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Herbalife', employees: '10,400+', hq: 'Los Angeles, USA', website: 'herbalife.com' },
      { name: 'Amway', employees: '17,000+', hq: 'Ada, USA', website: 'amway.com' },
      { name: 'NBTY', employees: '11,000+', hq: 'Ronkonkoma, USA', website: 'nbty.com' },
    ],
    highlights: [
      'Vitamins & minerals segment holds 35% market share, driven by immune health products',
      'Personalized nutrition supplements growing at 18% CAGR via D2C channels',
      'Asia Pacific is fastest-growing region with TCM (Traditional Chinese Medicine) integration',
    ],
    relatedMarkets: ['Sports Nutrition Market', 'Functional Food Market', 'Nutraceuticals Market'],
  },
  {
    slug: 'plant-based-food',
    title: 'Plant-Based Food',
    industry: 'Food Beverages & Tobacco',
    subIndustry: 'Plant-Based',
    region: 'global',
    type: 'Report',
    description: 'Plant-based food is transforming the protein economy, driven by environmental consciousness, health awareness, and technological improvements in taste and texture. Fermentation and precision biology are enabling next-gen products.',
    revenue: 24.3,
    forecast: 74.8,
    cagr: 17.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 8.2 }, { year: 2019, value: 11.4 }, { year: 2020, value: 14.8 },
      { year: 2021, value: 18.1 }, { year: 2022, value: 21.2 }, { year: 2023, value: 24.3 },
      { year: 2024, value: 29.2 }, { year: 2025, value: 35.1 }, { year: 2026, value: 42.8 },
      { year: 2027, value: 51.8 }, { year: 2028, value: 61.2 }, { year: 2029, value: 68.4 },
      { year: 2030, value: 74.8 },
    ],
    segments: ['Product Type', 'Source', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Beyond Meat', employees: '700+', hq: 'El Segundo, USA', website: 'beyondmeat.com' },
      { name: 'Impossible Foods', employees: '500+', hq: 'Redwood City, USA', website: 'impossiblefoods.com' },
      { name: 'Oatly', employees: '1,000+', hq: 'Malmö, Sweden', website: 'oatly.com' },
    ],
    highlights: [
      'Plant-based meat alternatives growing at 19% CAGR, led by burgers and sausages',
      'Dairy alternatives (oat milk, almond milk) account for 38% of category revenue',
      'Foodservice channel represents the fastest growth vector for plant-based penetration',
    ],
    relatedMarkets: ['Alternative Proteins Market', 'Dairy Alternatives Market', 'Functional Food Market'],
  },
  {
    slug: 'semiconductor',
    title: 'Semiconductor',
    industry: 'Semiconductor',
    subIndustry: 'Logic Chips',
    region: 'global',
    type: 'Report',
    description: 'The global semiconductor market is navigating post-boom normalization while AI accelerator demand creates new supercycles. Advanced packaging, chiplet architectures, and geopolitical reshoring are reshaping supply chains.',
    revenue: 526.8,
    forecast: 1118.2,
    cagr: 11.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 468.8 }, { year: 2019, value: 412.1 }, { year: 2020, value: 440.4 },
      { year: 2021, value: 555.9 }, { year: 2022, value: 574.1 }, { year: 2023, value: 526.8 },
      { year: 2024, value: 611.2 }, { year: 2025, value: 714.8 }, { year: 2026, value: 821.4 },
      { year: 2027, value: 921.8 }, { year: 2028, value: 1008.4 }, { year: 2029, value: 1068.2 },
      { year: 2030, value: 1118.2 },
    ],
    segments: ['Product Type', 'Application', 'Technology Node', 'Region'],
    companies: [
      { name: 'TSMC', employees: '73,000+', hq: 'Hsinchu, Taiwan', website: 'tsmc.com' },
      { name: 'Samsung Semiconductor', employees: '267,000+', hq: 'Seoul, South Korea', website: 'samsung.com' },
      { name: 'NVIDIA', employees: '29,600+', hq: 'Santa Clara, USA', website: 'nvidia.com' },
      { name: 'Intel', employees: '120,000+', hq: 'Santa Clara, USA', website: 'intel.com' },
    ],
    highlights: [
      'AI accelerators (GPU/NPU) are fastest-growing segment at 34% CAGR through 2030',
      'TSMC holds 57% of global foundry market share at advanced nodes',
      'US CHIPS Act driving $52B in domestic semiconductor fab investments',
    ],
    relatedMarkets: ['AI Chips Market', 'Memory Semiconductor Market', 'Power Semiconductor Market'],
  },
]
