import type { Market } from '@/types'

export const mockMarkets: Market[] = [
  {
    slug: 'monoclonal-antibodies',
    title: 'Monoclonal Antibodies',
    industry: 'Biotechnology',
    subIndustry: 'Monoclonal Antibodies',
    region: 'global',
    type: 'Report',
    description: 'The global monoclonal antibodies market is witnessing significant growth driven by rising prevalence of chronic diseases and cancer. Advanced biologics manufacturing capabilities are further supporting market expansion.',
    revenue: 211.4,
    forecast: 498.7,
    cagr: 11.2,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 115.2 }, { year: 2019, value: 130.8 }, { year: 2020, value: 148.1 },
      { year: 2021, value: 168.9 }, { year: 2022, value: 192.3 }, { year: 2023, value: 211.4 },
      { year: 2024, value: 235.0 }, { year: 2025, value: 261.8 }, { year: 2026, value: 291.5 },
      { year: 2027, value: 324.8 }, { year: 2028, value: 361.6 }, { year: 2029, value: 428.2 },
      { year: 2030, value: 498.7 },
    ],
    segments: ['Source Type', 'Production Type', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Roche', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'AbbVie', employees: '50,000+', hq: 'North Chicago, USA', website: 'abbvie.com' },
      { name: 'Regeneron Pharmaceuticals', employees: '11,000+', hq: 'Tarrytown, USA', website: 'regeneron.com' },
      { name: 'Bristol-Myers Squibb', employees: '32,200+', hq: 'New York, USA', website: 'bms.com' },
      { name: 'Johnson & Johnson', employees: '152,000+', hq: 'New Brunswick, USA', website: 'jnj.com' },
      { name: 'Novartis', employees: '108,000+', hq: 'Basel, Switzerland', website: 'novartis.com' },
      { name: 'Amgen', employees: '24,000+', hq: 'Thousand Oaks, USA', website: 'amgen.com' },
      { name: 'Pfizer', employees: '83,000+', hq: 'New York, USA', website: 'pfizer.com' },
    ],
    highlights: [
      'Cancer treatment remains the largest application segment, accounting for 45% of total market revenue',
      'Humanized monoclonal antibodies dominate with 65% market share due to reduced immunogenicity',
      'North America leads the global market, contributing over 42% of total revenues in 2023',
      'Biosimilar development is gaining traction as key patents expire, creating cost-effective alternatives',
      'Asia Pacific is projected to be the fastest-growing region with a CAGR of 14.2% through 2030',
    ],
    relatedMarkets: [
      'North America Monoclonal Antibodies Market', 'Europe Monoclonal Antibodies Market',
      'Bispecific Antibodies Market', 'Antibody Drug Conjugates Market',
      'Biosimilars Market', 'Cancer Immunotherapy Market',
    ],
  },
  {
    slug: 'electric-vehicles',
    title: 'Electric Vehicles',
    industry: 'Automotive & Transportation',
    subIndustry: 'Electric Vehicles',
    region: 'global',
    type: 'Report',
    description: 'The global electric vehicle market continues to accelerate as government mandates, falling battery costs, and expanding charging infrastructure drive mass adoption across passenger and commercial segments.',
    revenue: 388.1,
    forecast: 951.9,
    cagr: 13.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 102.3 }, { year: 2019, value: 126.7 }, { year: 2020, value: 143.9 },
      { year: 2021, value: 198.4 }, { year: 2022, value: 302.1 }, { year: 2023, value: 388.1 },
      { year: 2024, value: 445.2 }, { year: 2025, value: 523.8 }, { year: 2026, value: 621.0 },
      { year: 2027, value: 728.4 }, { year: 2028, value: 810.3 }, { year: 2029, value: 888.7 },
      { year: 2030, value: 951.9 },
    ],
    segments: ['Vehicle Type', 'Propulsion Type', 'Vehicle Class', 'End Use', 'Region'],
    companies: [
      { name: 'Tesla', employees: '127,855', hq: 'Austin, USA', website: 'tesla.com' },
      { name: 'BYD', employees: '570,000+', hq: 'Shenzhen, China', website: 'bydglobal.com' },
      { name: 'Volkswagen Group', employees: '684,000+', hq: 'Wolfsburg, Germany', website: 'volkswagen-group.com' },
      { name: 'General Motors', employees: '163,000', hq: 'Detroit, USA', website: 'gm.com' },
    ],
    highlights: [
      'Battery Electric Vehicles (BEVs) account for 71% of market share in 2023',
      'China dominates global EV adoption with 59% of new EV registrations',
      'Average EV battery cost has fallen 89% over the past decade to below $120/kWh',
      'Government incentives and stricter emission norms continue to accelerate adoption',
    ],
    relatedMarkets: [
      'EV Battery Market', 'EV Charging Infrastructure Market',
      'Autonomous Vehicle Market', 'Battery Management System Market',
    ],
  },
  {
    slug: 'solar-energy',
    title: 'Solar Energy',
    industry: 'Energy & Power',
    subIndustry: 'Solar Energy',
    region: 'global',
    type: 'Report',
    description: 'The global solar energy market is experiencing unprecedented growth as declining photovoltaic panel costs and strong policy support make solar one of the cheapest forms of new electricity generation.',
    revenue: 223.8,
    forecast: 612.4,
    cagr: 15.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 89.4 }, { year: 2019, value: 108.1 }, { year: 2020, value: 121.7 },
      { year: 2021, value: 155.3 }, { year: 2022, value: 194.2 }, { year: 2023, value: 223.8 },
      { year: 2024, value: 263.5 }, { year: 2025, value: 314.2 }, { year: 2026, value: 378.9 },
      { year: 2027, value: 449.3 }, { year: 2028, value: 512.8 }, { year: 2029, value: 563.7 },
      { year: 2030, value: 612.4 },
    ],
    segments: ['Technology', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'LONGi Green Energy', employees: '80,000+', hq: "Xi'an, China", website: 'longi.com' },
      { name: 'First Solar', employees: '9,800+', hq: 'Tempe, USA', website: 'firstsolar.com' },
      { name: 'Sunrun', employees: '15,000+', hq: 'San Francisco, USA', website: 'sunrun.com' },
    ],
    highlights: [
      'Utility-scale solar installations represent 65% of total capacity additions globally',
      'Solar panel costs have declined 90% over the last decade, now below $0.20/W',
      'India and China combined account for 45% of new solar capacity additions',
      'Floating solar installations grew 30% YoY driven by land scarcity concerns',
    ],
    relatedMarkets: ['Solar Panel Market', 'Solar Inverter Market', 'Energy Storage Market', 'Wind Energy Market'],
  },
  {
    slug: 'digital-health',
    title: 'Digital Health',
    industry: 'Healthcare',
    subIndustry: 'Digital Health',
    region: 'global',
    type: 'Report',
    description: 'The digital health market encompasses telemedicine, health IT, wearable devices, and AI-powered diagnostics. Increasing smartphone penetration and post-pandemic behavioral shifts are sustaining robust growth.',
    revenue: 211.0,
    forecast: 809.2,
    cagr: 21.2,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 86.4 }, { year: 2019, value: 101.2 }, { year: 2020, value: 152.8 },
      { year: 2021, value: 178.3 }, { year: 2022, value: 196.4 }, { year: 2023, value: 211.0 },
      { year: 2024, value: 268.4 }, { year: 2025, value: 341.7 }, { year: 2026, value: 428.3 },
      { year: 2027, value: 531.2 }, { year: 2028, value: 634.9 }, { year: 2029, value: 723.8 },
      { year: 2030, value: 809.2 },
    ],
    segments: ['Component', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Teladoc Health', employees: '14,000+', hq: 'Purchase, USA', website: 'teladochealth.com' },
      { name: 'Philips Healthcare', employees: '77,000+', hq: 'Amsterdam, Netherlands', website: 'philips.com' },
      { name: 'Epic Systems', employees: '10,000+', hq: 'Verona, USA', website: 'epic.com' },
    ],
    highlights: [
      'Telehealth segment led the market with 28% revenue share in 2023',
      'AI-powered diagnostics are projected to grow at 28% CAGR through 2030',
      'Remote patient monitoring adoption doubled post-COVID-19',
    ],
    relatedMarkets: ['Telehealth Market', 'Health IT Market', 'Wearable Medical Devices Market', 'AI in Healthcare Market'],
  },
  {
    slug: 'gene-therapy',
    title: 'Gene Therapy',
    industry: 'Biotechnology',
    subIndustry: 'Gene Therapy',
    region: 'global',
    type: 'Statistics',
    description: 'Gene therapy is revolutionizing treatment of genetic disorders, rare diseases, and oncology. Advances in viral vector manufacturing and CRISPR technologies are accelerating clinical pipeline development.',
    revenue: 6.8,
    forecast: 38.2,
    cagr: 28.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 1.2 }, { year: 2019, value: 1.9 }, { year: 2020, value: 2.8 },
      { year: 2021, value: 3.9 }, { year: 2022, value: 5.4 }, { year: 2023, value: 6.8 },
      { year: 2024, value: 9.2 }, { year: 2025, value: 12.4 }, { year: 2026, value: 16.8 },
      { year: 2027, value: 22.1 }, { year: 2028, value: 27.8 }, { year: 2029, value: 32.9 },
      { year: 2030, value: 38.2 },
    ],
    segments: ['Vector Type', 'Disease Indication', 'Delivery Mode', 'End Use', 'Region'],
    companies: [
      { name: 'Novartis', employees: '108,000+', hq: 'Basel, Switzerland', website: 'novartis.com' },
      { name: 'Bluebird Bio', employees: '1,400+', hq: 'Cambridge, USA', website: 'bluebirdbio.com' },
      { name: 'Spark Therapeutics', employees: '750+', hq: 'Philadelphia, USA', website: 'sparktx.com' },
    ],
    highlights: [
      'AAV-based gene therapies dominate the pipeline with over 65% of clinical trials using this vector',
      'Rare genetic disorders represent the largest disease indication segment',
      'CRISPR-based therapies advancing rapidly with first FDA approvals in 2023',
    ],
    relatedMarkets: ['Cell Therapy Market', 'CRISPR Technology Market', 'Rare Disease Treatment Market'],
  },
  {
    slug: 'surgical-robotics',
    title: 'Surgical Robotics',
    industry: 'MedTech',
    subIndustry: 'Surgical Robotics',
    region: 'global',
    type: 'Report',
    description: 'Surgical robotics systems are transforming minimally invasive surgery with enhanced precision and reduced recovery times. Growing surgical volumes and expanding robotic platform capabilities are driving adoption.',
    revenue: 14.7,
    forecast: 45.6,
    cagr: 17.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 5.2 }, { year: 2019, value: 6.4 }, { year: 2020, value: 6.9 },
      { year: 2021, value: 8.7 }, { year: 2022, value: 11.8 }, { year: 2023, value: 14.7 },
      { year: 2024, value: 17.9 }, { year: 2025, value: 21.8 }, { year: 2026, value: 26.4 },
      { year: 2027, value: 31.8 }, { year: 2028, value: 37.2 }, { year: 2029, value: 41.8 },
      { year: 2030, value: 45.6 },
    ],
    segments: ['Product Type', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Intuitive Surgical', employees: '12,000+', hq: 'Sunnyvale, USA', website: 'intuitivesurgical.com' },
      { name: 'Medtronic', employees: '95,000+', hq: 'Dublin, Ireland', website: 'medtronic.com' },
      { name: 'Stryker', employees: '51,000+', hq: 'Kalamazoo, USA', website: 'stryker.com' },
    ],
    highlights: [
      'Da Vinci system by Intuitive Surgical holds ~55% global market share',
      'Orthopaedic robotic surgery growing fastest at 22% CAGR',
      'AI integration enabling real-time surgical guidance and outcome prediction',
    ],
    relatedMarkets: ['Minimally Invasive Surgery Market', 'Orthopedic Implants Market', 'Operating Room Equipment Market'],
  },
  {
    slug: 'molecular-diagnostics',
    title: 'Molecular Diagnostics',
    industry: 'Clinical Diagnostics',
    subIndustry: 'Molecular Diagnostics',
    region: 'global',
    type: 'Databook',
    description: 'Molecular diagnostics leverages DNA, RNA, and protein biomarker detection for infectious disease, oncology, and genetic testing. Post-COVID infrastructure investments are fueling sustained market growth.',
    revenue: 17.8,
    forecast: 42.3,
    cagr: 13.3,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 8.2 }, { year: 2019, value: 9.8 }, { year: 2020, value: 18.6 },
      { year: 2021, value: 22.4 }, { year: 2022, value: 19.1 }, { year: 2023, value: 17.8 },
      { year: 2024, value: 20.2 }, { year: 2025, value: 23.4 }, { year: 2026, value: 27.1 },
      { year: 2027, value: 31.3 }, { year: 2028, value: 35.2 }, { year: 2029, value: 38.9 },
      { year: 2030, value: 42.3 },
    ],
    segments: ['Technology', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'Roche Diagnostics', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'Abbott', employees: '113,000+', hq: 'Abbott Park, USA', website: 'abbott.com' },
      { name: 'Qiagen', employees: '6,200+', hq: 'Hilden, Germany', website: 'qiagen.com' },
    ],
    highlights: [
      'PCR technology remains dominant with 38% revenue share in 2023',
      'NGS-based diagnostics growing at 18% CAGR driven by oncology applications',
      'Point-of-care molecular testing expanding rapidly in low-resource settings',
    ],
    relatedMarkets: ['Point-of-Care Testing Market', 'NGS Market', 'Infectious Disease Diagnostics Market'],
  },
  {
    slug: 'ev-battery',
    title: 'EV Battery',
    industry: 'Automotive & Transportation',
    subIndustry: 'Electric Vehicles',
    region: 'global',
    type: 'Statistics',
    description: 'The EV battery market is the cornerstone of the electric mobility revolution. Declining lithium-ion costs, solid-state battery development, and gigafactory expansions are reshaping the competitive landscape.',
    revenue: 92.4,
    forecast: 387.3,
    cagr: 22.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 18.2 }, { year: 2019, value: 25.1 }, { year: 2020, value: 32.8 },
      { year: 2021, value: 48.6 }, { year: 2022, value: 72.3 }, { year: 2023, value: 92.4 },
      { year: 2024, value: 122.8 }, { year: 2025, value: 161.4 }, { year: 2026, value: 208.3 },
      { year: 2027, value: 261.7 }, { year: 2028, value: 310.2 }, { year: 2029, value: 352.8 },
      { year: 2030, value: 387.3 },
    ],
    segments: ['Battery Type', 'Vehicle Type', 'Capacity', 'Region'],
    companies: [
      { name: 'CATL', employees: '92,000+', hq: 'Ningde, China', website: 'catl.com' },
      { name: 'LG Energy Solution', employees: '30,000+', hq: 'Seoul, South Korea', website: 'lges.com' },
      { name: 'Panasonic', employees: '240,000+', hq: 'Osaka, Japan', website: 'panasonic.com' },
    ],
    highlights: [
      'CATL holds 37% global EV battery market share in 2023',
      'Solid-state batteries expected to reach commercial scale by 2027',
      'Lithium iron phosphate (LFP) chemistry gaining share due to lower cost',
    ],
    relatedMarkets: ['Electric Vehicles Market', 'Battery Management Systems Market', 'Lithium Mining Market'],
  },
  {
    slug: 'oncology-drugs',
    title: 'Oncology Drugs',
    industry: 'Pharmaceuticals',
    subIndustry: 'Oncology',
    region: 'global',
    type: 'Report',
    description: 'The oncology drugs market remains the largest therapeutic segment in pharmaceuticals. Immunotherapy, targeted therapy, and cell therapy innovations continue to expand treatment options across cancer types.',
    revenue: 248.6,
    forecast: 598.4,
    cagr: 13.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 118.4 }, { year: 2019, value: 138.7 }, { year: 2020, value: 153.2 },
      { year: 2021, value: 178.9 }, { year: 2022, value: 214.3 }, { year: 2023, value: 248.6 },
      { year: 2024, value: 291.2 }, { year: 2025, value: 341.8 }, { year: 2026, value: 398.4 },
      { year: 2027, value: 458.2 }, { year: 2028, value: 518.7 }, { year: 2029, value: 561.3 },
      { year: 2030, value: 598.4 },
    ],
    segments: ['Drug Class', 'Cancer Type', 'Therapy Line', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Roche', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'Bristol-Myers Squibb', employees: '32,200+', hq: 'New York, USA', website: 'bms.com' },
      { name: 'Merck & Co.', employees: '68,000+', hq: 'Rahway, USA', website: 'merck.com' },
      { name: 'AstraZeneca', employees: '83,000+', hq: 'Cambridge, UK', website: 'astrazeneca.com' },
    ],
    highlights: [
      'Checkpoint inhibitors (PD-1/PD-L1) are the largest drug class with 31% revenue share',
      'CAR-T cell therapies gaining traction, with 8 FDA-approved products as of 2024',
      'Lung cancer remains the largest indication driving oncology drug revenue',
    ],
    relatedMarkets: ['Immunotherapy Market', 'CAR-T Cell Therapy Market', 'Cancer Diagnostics Market'],
  },
  {
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    industry: 'Telecom & Technology',
    subIndustry: 'Cybersecurity',
    region: 'global',
    type: 'Report',
    description: 'The global cybersecurity market is driven by escalating ransomware attacks, regulatory compliance requirements, and digital transformation across enterprises. Zero-trust architecture adoption is reshaping enterprise security stacks.',
    revenue: 202.7,
    forecast: 562.7,
    cagr: 15.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 102.1 }, { year: 2019, value: 120.9 }, { year: 2020, value: 137.6 },
      { year: 2021, value: 155.8 }, { year: 2022, value: 180.2 }, { year: 2023, value: 202.7 },
      { year: 2024, value: 241.1 }, { year: 2025, value: 287.3 }, { year: 2026, value: 341.8 },
      { year: 2027, value: 403.2 }, { year: 2028, value: 466.4 }, { year: 2029, value: 517.9 },
      { year: 2030, value: 562.7 },
    ],
    segments: ['Solution', 'Service', 'Deployment', 'Organization Size', 'Vertical', 'Region'],
    companies: [
      { name: 'Palo Alto Networks', employees: '14,000+', hq: 'Santa Clara, USA', website: 'paloaltonetworks.com' },
      { name: 'CrowdStrike', employees: '9,800+', hq: 'Austin, USA', website: 'crowdstrike.com' },
      { name: 'Fortinet', employees: '12,700+', hq: 'Sunnyvale, USA', website: 'fortinet.com' },
      { name: 'Microsoft', employees: '221,000+', hq: 'Redmond, USA', website: 'microsoft.com' },
    ],
    highlights: [
      'Cloud security is the fastest-growing segment at 24% CAGR through 2030',
      'AI-driven threat detection becoming standard in endpoint security platforms',
      'Ransomware attacks increased 73% in 2023, driving enterprise security budgets',
    ],
    relatedMarkets: ['Cloud Security Market', 'Zero Trust Security Market', 'Identity & Access Management Market'],
  },
  {
    slug: 'fintech',
    title: 'Fintech',
    industry: 'Financial Services',
    subIndustry: 'Fintech',
    region: 'global',
    type: 'Report',
    description: 'Fintech is disrupting traditional banking and financial services through digital payments, embedded finance, and AI-driven credit scoring. Emerging markets are particularly driving mobile-first financial inclusion.',
    revenue: 312.4,
    forecast: 1152.1,
    cagr: 20.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 89.3 }, { year: 2019, value: 118.6 }, { year: 2020, value: 148.3 },
      { year: 2021, value: 192.7 }, { year: 2022, value: 258.4 }, { year: 2023, value: 312.4 },
      { year: 2024, value: 388.6 }, { year: 2025, value: 491.3 }, { year: 2026, value: 618.7 },
      { year: 2027, value: 771.4 }, { year: 2028, value: 918.2 }, { year: 2029, value: 1042.8 },
      { year: 2030, value: 1152.1 },
    ],
    segments: ['Service', 'Technology', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Stripe', employees: '8,000+', hq: 'San Francisco, USA', website: 'stripe.com' },
      { name: 'PayPal', employees: '29,900+', hq: 'San Jose, USA', website: 'paypal.com' },
      { name: 'Ant Group', employees: '28,000+', hq: 'Hangzhou, China', website: 'antgroup.com' },
      { name: 'Revolut', employees: '8,000+', hq: 'London, UK', website: 'revolut.com' },
    ],
    highlights: [
      'Digital payments represent 54% of total fintech revenue in 2023',
      'BNPL (Buy Now Pay Later) growing at 26% CAGR as consumer credit shifts',
      'Embedded finance projected to reach $384B by 2030',
    ],
    relatedMarkets: ['Digital Payments Market', 'InsurTech Market', 'RegTech Market', 'Blockchain Market'],
  },
  {
    slug: 'cloud-computing',
    title: 'Cloud Computing',
    industry: 'Telecom & Technology',
    subIndustry: 'Cloud Computing',
    region: 'global',
    type: 'Databook',
    description: 'Cloud computing underpins the digital economy with IaaS, PaaS, and SaaS solutions. Generative AI workloads, hybrid cloud adoption, and edge computing are creating new growth vectors for hyperscalers.',
    revenue: 591.8,
    forecast: 2376.4,
    cagr: 21.9,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 182.3 }, { year: 2019, value: 233.4 }, { year: 2020, value: 312.1 },
      { year: 2021, value: 408.9 }, { year: 2022, value: 501.3 }, { year: 2023, value: 591.8 },
      { year: 2024, value: 742.6 }, { year: 2025, value: 928.4 }, { year: 2026, value: 1148.2 },
      { year: 2027, value: 1412.8 }, { year: 2028, value: 1718.4 }, { year: 2029, value: 2058.7 },
      { year: 2030, value: 2376.4 },
    ],
    segments: ['Service Model', 'Deployment Model', 'Enterprise Size', 'Industry Vertical', 'Region'],
    companies: [
      { name: 'Amazon Web Services', employees: '1,600,000+', hq: 'Seattle, USA', website: 'aws.amazon.com' },
      { name: 'Microsoft Azure', employees: '221,000+', hq: 'Redmond, USA', website: 'azure.microsoft.com' },
      { name: 'Google Cloud', employees: '182,000+', hq: 'Mountain View, USA', website: 'cloud.google.com' },
    ],
    highlights: [
      'AWS, Azure, and Google Cloud collectively hold 66% of global cloud market share',
      'Generative AI infrastructure spending driving 35% increase in cloud capex in 2024',
      'Multi-cloud adoption reaches 87% among enterprise organizations',
    ],
    relatedMarkets: ['AI Infrastructure Market', 'Edge Computing Market', 'Serverless Computing Market'],
  },
  {
    slug: 'pharmaceutical-packaging',
    title: 'Pharmaceutical Packaging',
    industry: 'Packaging',
    subIndustry: 'Flexible Packaging',
    region: 'global',
    type: 'Databook',
    description: 'Pharmaceutical packaging ensures drug safety, compliance, and patient adherence. Growing biologics pipelines requiring specialized cold-chain packaging and rising unit dose demand are key market drivers.',
    revenue: 123.4,
    forecast: 248.7,
    cagr: 10.6,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 71.2 }, { year: 2019, value: 79.4 }, { year: 2020, value: 88.1 },
      { year: 2021, value: 97.8 }, { year: 2022, value: 111.3 }, { year: 2023, value: 123.4 },
      { year: 2024, value: 136.8 }, { year: 2025, value: 151.2 }, { year: 2026, value: 167.4 },
      { year: 2027, value: 185.6 }, { year: 2028, value: 206.3 }, { year: 2029, value: 227.8 },
      { year: 2030, value: 248.7 },
    ],
    segments: ['Material', 'Product Type', 'Drug Type', 'Region'],
    companies: [
      { name: 'Amcor', employees: '44,000+', hq: 'Zurich, Switzerland', website: 'amcor.com' },
      { name: 'Berry Global', employees: '48,000+', hq: 'Evansville, USA', website: 'berryglobal.com' },
      { name: 'Gerresheimer', employees: '11,400+', hq: 'Düsseldorf, Germany', website: 'gerresheimer.com' },
    ],
    highlights: [
      'Blister packaging dominates with 42% revenue share in solid dose pharmaceuticals',
      'Prefillable syringes growing at 12% CAGR driven by biologics administration',
      'Smart packaging with RFID and temperature indicators gaining regulatory traction',
    ],
    relatedMarkets: ['Drug Delivery Systems Market', 'Cold Chain Packaging Market', 'Sustainable Packaging Market'],
  },
  {
    slug: 'ai-in-healthcare',
    title: 'AI in Healthcare',
    industry: 'Healthcare',
    subIndustry: 'Health IT',
    region: 'global',
    type: 'Statistics',
    description: 'AI in healthcare is transforming diagnostics, drug discovery, clinical operations, and patient engagement. Large language models and multimodal AI are emerging as the next frontier in clinical decision support.',
    revenue: 19.8,
    forecast: 187.9,
    cagr: 37.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 2.1 }, { year: 2019, value: 3.4 }, { year: 2020, value: 5.8 },
      { year: 2021, value: 8.9 }, { year: 2022, value: 13.9 }, { year: 2023, value: 19.8 },
      { year: 2024, value: 30.1 }, { year: 2025, value: 46.2 }, { year: 2026, value: 69.8 },
      { year: 2027, value: 100.4 }, { year: 2028, value: 133.7 }, { year: 2029, value: 162.8 },
      { year: 2030, value: 187.9 },
    ],
    segments: ['Component', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'IBM Watson Health', employees: '350,000+', hq: 'Armonk, USA', website: 'ibm.com' },
      { name: 'Google Health', employees: '182,000+', hq: 'Mountain View, USA', website: 'health.google' },
      { name: 'Tempus AI', employees: '3,000+', hq: 'Chicago, USA', website: 'tempus.com' },
    ],
    highlights: [
      'Medical imaging AI is the largest application segment at 29% revenue share',
      'Drug discovery AI reduces preclinical timelines by up to 40%',
      'NLP-based clinical documentation tools adopted by 62% of US health systems',
    ],
    relatedMarkets: ['Digital Health Market', 'Radiology AI Market', 'AI Drug Discovery Market'],
  },
  {
    slug: 'wind-energy',
    title: 'Wind Energy',
    industry: 'Energy & Power',
    subIndustry: 'Wind Energy',
    region: 'global',
    type: 'Statistics',
    description: 'Wind energy is a cornerstone of global renewable energy transition. Offshore wind expansion, turbine technology improvements, and favorable policy frameworks are driving capacity additions worldwide.',
    revenue: 108.2,
    forecast: 298.4,
    cagr: 15.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 54.3 }, { year: 2019, value: 63.8 }, { year: 2020, value: 74.1 },
      { year: 2021, value: 84.9 }, { year: 2022, value: 97.4 }, { year: 2023, value: 108.2 },
      { year: 2024, value: 128.7 }, { year: 2025, value: 153.2 }, { year: 2026, value: 182.8 },
      { year: 2027, value: 216.4 }, { year: 2028, value: 251.8 }, { year: 2029, value: 276.2 },
      { year: 2030, value: 298.4 },
    ],
    segments: ['Type', 'Component', 'Location', 'Capacity', 'Region'],
    companies: [
      { name: 'Vestas', employees: '29,000+', hq: 'Aarhus, Denmark', website: 'vestas.com' },
      { name: 'Siemens Gamesa', employees: '27,000+', hq: 'Zamudio, Spain', website: 'siemensgamesa.com' },
      { name: 'GE Vernova', employees: '80,000+', hq: 'Cambridge, USA', website: 'gevernova.com' },
    ],
    highlights: [
      'Offshore wind capacity additions surpassed onshore for first time in Europe in 2023',
      'Floating offshore wind technology unlocking deeper water deployment',
      'China accounts for 60% of global new onshore wind installations',
    ],
    relatedMarkets: ['Solar Energy Market', 'Energy Storage Market', 'Offshore Wind Market'],
  },
  {
    slug: 'point-of-care-testing',
    title: 'Point-of-Care Testing',
    industry: 'Clinical Diagnostics',
    subIndustry: 'Point-of-Care Testing',
    region: 'global',
    type: 'Statistics',
    description: 'Point-of-care testing enables rapid diagnostic results outside traditional laboratory settings. Post-pandemic infrastructure and home testing normalization are creating sustained demand growth.',
    revenue: 48.3,
    forecast: 102.7,
    cagr: 11.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 21.4 }, { year: 2019, value: 25.1 }, { year: 2020, value: 42.8 },
      { year: 2021, value: 51.2 }, { year: 2022, value: 53.4 }, { year: 2023, value: 48.3 },
      { year: 2024, value: 55.1 }, { year: 2025, value: 63.2 }, { year: 2026, value: 72.8 },
      { year: 2027, value: 82.4 }, { year: 2028, value: 90.6 }, { year: 2029, value: 97.4 },
      { year: 2030, value: 102.7 },
    ],
    segments: ['Product', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'Abbott', employees: '113,000+', hq: 'Abbott Park, USA', website: 'abbott.com' },
      { name: 'Roche Diagnostics', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'bioMérieux', employees: '14,200+', hq: 'Marcy-l\'Étoile, France', website: 'biomerieux.com' },
    ],
    highlights: [
      'Infectious disease testing accounts for 42% of POCT revenue in 2023',
      'Home testing kits market growing at 18% CAGR post-COVID normalization',
      'Lateral flow assays remain most widely used POCT format globally',
    ],
    relatedMarkets: ['Molecular Diagnostics Market', 'Immunoassay Market', 'Home Diagnostics Market'],
  },
  {
    slug: 'sports-nutrition',
    title: 'Sports Nutrition',
    industry: 'Nutrition',
    subIndustry: 'Sports Nutrition',
    region: 'global',
    type: 'Databook',
    description: 'The sports nutrition market is expanding beyond athletes to encompass fitness enthusiasts, aging populations, and preventive health consumers. Protein supplements, energy products, and recovery formulations lead demand.',
    revenue: 47.2,
    forecast: 98.4,
    cagr: 11.1,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 26.8 }, { year: 2019, value: 30.2 }, { year: 2020, value: 32.1 },
      { year: 2021, value: 37.4 }, { year: 2022, value: 42.8 }, { year: 2023, value: 47.2 },
      { year: 2024, value: 52.4 }, { year: 2025, value: 58.3 }, { year: 2026, value: 65.4 },
      { year: 2027, value: 73.2 }, { year: 2028, value: 81.8 }, { year: 2029, value: 90.4 },
      { year: 2030, value: 98.4 },
    ],
    segments: ['Product Type', 'Form', 'Distribution Channel', 'Consumer Type', 'Region'],
    companies: [
      { name: 'Glanbia', employees: '6,500+', hq: 'Kilkenny, Ireland', website: 'glanbia.com' },
      { name: 'Abbott Nutrition', employees: '113,000+', hq: 'Abbott Park, USA', website: 'abbott.com' },
      { name: 'PepsiCo', employees: '315,000+', hq: 'Purchase, USA', website: 'pepsico.com' },
    ],
    highlights: [
      'Protein supplements hold largest product share at 38% in 2023',
      'Plant-based protein demand growing at 15% CAGR among fitness consumers',
      'E-commerce channels now represent 35% of sports nutrition sales globally',
    ],
    relatedMarkets: ['Dietary Supplements Market', 'Functional Food Market', 'Probiotic Market'],
  },
  {
    slug: '5g-infrastructure',
    title: '5G Infrastructure',
    industry: 'Telecom & Technology',
    subIndustry: '5G',
    region: 'global',
    type: 'Report',
    description: '5G infrastructure buildout is accelerating across developed and emerging markets, enabling ultra-low latency applications in autonomous vehicles, industrial IoT, and immersive media experiences.',
    revenue: 74.8,
    forecast: 312.4,
    cagr: 22.6,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 4.2 }, { year: 2019, value: 8.9 }, { year: 2020, value: 18.4 },
      { year: 2021, value: 32.1 }, { year: 2022, value: 54.3 }, { year: 2023, value: 74.8 },
      { year: 2024, value: 98.2 }, { year: 2025, value: 132.4 }, { year: 2026, value: 175.8 },
      { year: 2027, value: 219.4 }, { year: 2028, value: 258.7 }, { year: 2029, value: 289.3 },
      { year: 2030, value: 312.4 },
    ],
    segments: ['Component', 'Frequency', 'Network Architecture', 'End User', 'Region'],
    companies: [
      { name: 'Ericsson', employees: '110,000+', hq: 'Stockholm, Sweden', website: 'ericsson.com' },
      { name: 'Nokia', employees: '86,000+', hq: 'Espoo, Finland', website: 'nokia.com' },
      { name: 'Huawei', employees: '207,000+', hq: 'Shenzhen, China', website: 'huawei.com' },
    ],
    highlights: [
      'China leads global 5G base station deployments with 2.3M stations by end-2023',
      'Private 5G networks for industrial IoT growing at 28% CAGR',
      'Open RAN architecture gaining traction among Tier 2 and Tier 3 operators',
    ],
    relatedMarkets: ['IoT Market', 'Network Slicing Market', 'Edge Computing Market'],
  },
  {
    slug: 'dietary-supplements',
    title: 'Dietary Supplements',
    industry: 'Nutrition',
    subIndustry: 'Dietary Supplements',
    region: 'global',
    type: 'Databook',
    description: 'Dietary supplements market spans vitamins, minerals, botanicals, and specialty ingredients. Consumer self-care trends, aging demographics, and preventive healthcare shifts are driving consistent category growth.',
    revenue: 178.8,
    forecast: 381.2,
    cagr: 11.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 96.4 }, { year: 2019, value: 109.3 }, { year: 2020, value: 132.8 },
      { year: 2021, value: 151.9 }, { year: 2022, value: 167.4 }, { year: 2023, value: 178.8 },
      { year: 2024, value: 199.2 }, { year: 2025, value: 222.4 }, { year: 2026, value: 248.3 },
      { year: 2027, value: 278.4 }, { year: 2028, value: 311.8 }, { year: 2029, value: 347.2 },
      { year: 2030, value: 381.2 },
    ],
    segments: ['Product Type', 'Form', 'Application', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Herbalife', employees: '10,400+', hq: 'Los Angeles, USA', website: 'herbalife.com' },
      { name: 'Amway', employees: '17,000+', hq: 'Ada, USA', website: 'amway.com' },
      { name: 'NBTY', employees: '11,000+', hq: 'Ronkonkoma, USA', website: 'nbty.com' },
    ],
    highlights: [
      'Vitamins & minerals segment holds 35% market share, driven by immune health products',
      'Personalized nutrition supplements growing at 18% CAGR via D2C channels',
      'Asia Pacific is fastest-growing region with TCM (Traditional Chinese Medicine) integration',
    ],
    relatedMarkets: ['Sports Nutrition Market', 'Functional Food Market', 'Nutraceuticals Market'],
  },
  {
    slug: 'plant-based-food',
    title: 'Plant-Based Food',
    industry: 'Food Beverages & Tobacco',
    subIndustry: 'Plant-Based',
    region: 'global',
    type: 'Report',
    description: 'Plant-based food is transforming the protein economy, driven by environmental consciousness, health awareness, and technological improvements in taste and texture. Fermentation and precision biology are enabling next-gen products.',
    revenue: 24.3,
    forecast: 74.8,
    cagr: 17.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 8.2 }, { year: 2019, value: 11.4 }, { year: 2020, value: 14.8 },
      { year: 2021, value: 18.1 }, { year: 2022, value: 21.2 }, { year: 2023, value: 24.3 },
      { year: 2024, value: 29.2 }, { year: 2025, value: 35.1 }, { year: 2026, value: 42.8 },
      { year: 2027, value: 51.8 }, { year: 2028, value: 61.2 }, { year: 2029, value: 68.4 },
      { year: 2030, value: 74.8 },
    ],
    segments: ['Product Type', 'Source', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Beyond Meat', employees: '700+', hq: 'El Segundo, USA', website: 'beyondmeat.com' },
      { name: 'Impossible Foods', employees: '500+', hq: 'Redwood City, USA', website: 'impossiblefoods.com' },
      { name: 'Oatly', employees: '1,000+', hq: 'Malmö, Sweden', website: 'oatly.com' },
    ],
    highlights: [
      'Plant-based meat alternatives growing at 19% CAGR, led by burgers and sausages',
      'Dairy alternatives (oat milk, almond milk) account for 38% of category revenue',
      'Foodservice channel represents the fastest growth vector for plant-based penetration',
    ],
    relatedMarkets: ['Alternative Proteins Market', 'Dairy Alternatives Market', 'Functional Food Market'],
  },
  {
    slug: 'semiconductor',
    title: 'Semiconductor',
    industry: 'Semiconductor',
    subIndustry: 'Logic Chips',
    region: 'global',
    type: 'Report',
    description: 'The global semiconductor market is navigating post-boom normalization while AI accelerator demand creates new supercycles. Advanced packaging, chiplet architectures, and geopolitical reshoring are reshaping supply chains.',
    revenue: 526.8,
    forecast: 1118.2,
    cagr: 11.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 468.8 }, { year: 2019, value: 412.1 }, { year: 2020, value: 440.4 },
      { year: 2021, value: 555.9 }, { year: 2022, value: 574.1 }, { year: 2023, value: 526.8 },
      { year: 2024, value: 611.2 }, { year: 2025, value: 714.8 }, { year: 2026, value: 821.4 },
      { year: 2027, value: 921.8 }, { year: 2028, value: 1008.4 }, { year: 2029, value: 1068.2 },
      { year: 2030, value: 1118.2 },
    ],
    segments: ['Product Type', 'Application', 'Technology Node', 'Region'],
    companies: [
      { name: 'TSMC', employees: '73,000+', hq: 'Hsinchu, Taiwan', website: 'tsmc.com' },
      { name: 'Samsung Semiconductor', employees: '267,000+', hq: 'Seoul, South Korea', website: 'samsung.com' },
      { name: 'NVIDIA', employees: '29,600+', hq: 'Santa Clara, USA', website: 'nvidia.com' },
      { name: 'Intel', employees: '120,000+', hq: 'Santa Clara, USA', website: 'intel.com' },
    ],
    highlights: [
      'AI accelerators (GPU/NPU) are fastest-growing segment at 34% CAGR through 2030',
      'TSMC holds 57% of global foundry market share at advanced nodes',
      'US CHIPS Act driving $52B in domestic semiconductor fab investments',
    ],
    relatedMarkets: ['AI Chips Market', 'Memory Semiconductor Market', 'Power Semiconductor Market'],
  },

  // ── Aerospace & Defence ──────────────────────────────────────────────────
  {
    slug: 'commercial-aviation',
    title: 'Commercial Aviation',
    industry: 'Aerospace & Defence',
    subIndustry: 'Commercial Aviation',
    region: 'global',
    type: 'Report',
    description: 'The commercial aviation market is in full post-pandemic recovery, with passenger traffic surpassing 2019 levels. Fleet expansion, narrowbody aircraft demand, and sustainable aviation fuel adoption are reshaping the competitive landscape.',
    revenue: 343.2,
    forecast: 741.8,
    cagr: 11.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 312.8 }, { year: 2019, value: 338.4 }, { year: 2020, value: 124.2 },
      { year: 2021, value: 198.4 }, { year: 2022, value: 291.7 }, { year: 2023, value: 343.2 },
      { year: 2024, value: 392.8 }, { year: 2025, value: 448.4 }, { year: 2026, value: 511.2 },
      { year: 2027, value: 578.4 }, { year: 2028, value: 638.2 }, { year: 2029, value: 693.4 },
      { year: 2030, value: 741.8 },
    ],
    segments: ['Aircraft Type', 'Service', 'Seat Class', 'Route Type', 'Region'],
    companies: [
      { name: 'Boeing', employees: '156,000+', hq: 'Arlington, USA', website: 'boeing.com' },
      { name: 'Airbus', employees: '134,000+', hq: 'Toulouse, France', website: 'airbus.com' },
      { name: 'Delta Air Lines', employees: '90,000+', hq: 'Atlanta, USA', website: 'delta.com' },
      { name: 'United Airlines', employees: '92,000+', hq: 'Chicago, USA', website: 'united.com' },
    ],
    highlights: [
      'Narrowbody aircraft account for 68% of new aircraft orders driven by fuel efficiency demands',
      'Asia Pacific leads passenger growth with CAGR of 14.2% through 2030',
      'Sustainable Aviation Fuel (SAF) mandates increasing production capacity fivefold by 2030',
      'MRO services represent $102B opportunity as global fleet ages and expands',
    ],
    relatedMarkets: ['Aircraft MRO Market', 'Sustainable Aviation Fuel Market', 'Aerospace Defense Market', 'Drone Market'],
  },
  {
    slug: 'defense-systems',
    title: 'Defense Systems',
    industry: 'Aerospace & Defence',
    subIndustry: 'Defense Systems',
    region: 'global',
    type: 'Databook',
    description: 'Global defense spending is at a multi-decade high as geopolitical instability drives NATO members to increase budgets. Advanced missile systems, electronic warfare, and next-gen fighter programs dominate procurement.',
    revenue: 421.8,
    forecast: 812.4,
    cagr: 9.8,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 278.4 }, { year: 2019, value: 298.1 }, { year: 2020, value: 318.7 },
      { year: 2021, value: 341.2 }, { year: 2022, value: 381.8 }, { year: 2023, value: 421.8 },
      { year: 2024, value: 463.4 }, { year: 2025, value: 508.8 }, { year: 2026, value: 558.4 },
      { year: 2027, value: 612.8 }, { year: 2028, value: 668.4 }, { year: 2029, value: 741.2 },
      { year: 2030, value: 812.4 },
    ],
    segments: ['System Type', 'Platform', 'Technology', 'End User', 'Region'],
    companies: [
      { name: 'Lockheed Martin', employees: '116,000+', hq: 'Bethesda, USA', website: 'lockheedmartin.com' },
      { name: 'Raytheon Technologies', employees: '185,000+', hq: 'Arlington, USA', website: 'rtx.com' },
      { name: 'Northrop Grumman', employees: '95,000+', hq: 'Falls Church, USA', website: 'northropgrumman.com' },
      { name: 'BAE Systems', employees: '93,000+', hq: 'London, UK', website: 'baesystems.com' },
    ],
    highlights: [
      'NATO members increased defense budgets by an aggregate $78B in 2023 alone',
      'Hypersonic missile systems represent the highest-priority procurement across all major powers',
      'AI-enabled autonomous defense systems attracting $24B in R&D investment',
      'Cybersecurity defense emerging as fifth warfare domain with dedicated budget lines',
    ],
    relatedMarkets: ['Military Aircraft Market', 'Naval Defense Market', 'Space Defense Market', 'Cybersecurity Market'],
  },
  {
    slug: 'space-technology',
    title: 'Space Technology',
    industry: 'Aerospace & Defence',
    subIndustry: 'Space Technology',
    region: 'global',
    type: 'Statistics',
    description: 'The commercial space economy is expanding rapidly as launch costs plummet and satellite constellations proliferate. New Space ventures in broadband internet, Earth observation, and lunar exploration are driving unprecedented investment.',
    revenue: 58.4,
    forecast: 198.2,
    cagr: 19.1,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 18.4 }, { year: 2019, value: 22.8 }, { year: 2020, value: 27.4 },
      { year: 2021, value: 34.2 }, { year: 2022, value: 46.8 }, { year: 2023, value: 58.4 },
      { year: 2024, value: 72.8 }, { year: 2025, value: 91.4 }, { year: 2026, value: 114.2 },
      { year: 2027, value: 138.4 }, { year: 2028, value: 161.8 }, { year: 2029, value: 181.4 },
      { year: 2030, value: 198.2 },
    ],
    segments: ['Segment', 'Orbit Type', 'Launch Vehicle', 'Application', 'Region'],
    companies: [
      { name: 'SpaceX', employees: '13,000+', hq: 'Hawthorne, USA', website: 'spacex.com' },
      { name: 'Planet Labs', employees: '900+', hq: 'San Francisco, USA', website: 'planet.com' },
      { name: 'OneWeb', employees: '700+', hq: 'London, UK', website: 'oneweb.net' },
    ],
    highlights: [
      'SpaceX Starlink constellation surpassed 6,000 satellites, covering 100+ countries',
      'Reusable launch vehicles have cut launch costs by 95% over the past decade',
      'Earth observation data market growing at 22% CAGR driven by climate monitoring demand',
    ],
    relatedMarkets: ['Satellite Market', 'Launch Services Market', 'Space Situational Awareness Market'],
  },

  // ── Animal Health ────────────────────────────────────────────────────────
  {
    slug: 'animal-vaccines',
    title: 'Animal Vaccines',
    industry: 'Animal Health',
    subIndustry: 'Vaccines',
    region: 'global',
    type: 'Report',
    description: 'The animal vaccines market is expanding as livestock producers intensify biosecurity protocols and companion animal owners invest in preventive care. mRNA vaccine technology validated in human health is now being adapted for veterinary use.',
    revenue: 11.4,
    forecast: 24.8,
    cagr: 11.8,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 6.2 }, { year: 2019, value: 7.1 }, { year: 2020, value: 7.8 },
      { year: 2021, value: 8.8 }, { year: 2022, value: 10.2 }, { year: 2023, value: 11.4 },
      { year: 2024, value: 12.8 }, { year: 2025, value: 14.4 }, { year: 2026, value: 16.2 },
      { year: 2027, value: 18.3 }, { year: 2028, value: 20.4 }, { year: 2029, value: 22.6 },
      { year: 2030, value: 24.8 },
    ],
    segments: ['Animal Type', 'Vaccine Type', 'Route of Administration', 'Disease Indication', 'Region'],
    companies: [
      { name: 'Zoetis', employees: '14,500+', hq: 'Parsippany, USA', website: 'zoetis.com' },
      { name: 'Merck Animal Health', employees: '68,000+', hq: 'Rahway, USA', website: 'merck-animal-health.com' },
      { name: 'Boehringer Ingelheim Animal Health', employees: '52,000+', hq: 'Ingelheim, Germany', website: 'boehringer-ingelheim.com' },
    ],
    highlights: [
      'Livestock vaccines account for 62% of market revenue, led by poultry and swine segments',
      'Companion animal vaccine demand growing at 14% CAGR driven by pet humanization trends',
      'mRNA-based veterinary vaccines entering clinical development for avian influenza and ASF',
    ],
    relatedMarkets: ['Animal Diagnostics Market', 'Veterinary Drugs Market', 'Feed Additives Market'],
  },
  {
    slug: 'veterinary-diagnostics',
    title: 'Veterinary Diagnostics',
    industry: 'Animal Health',
    subIndustry: 'Diagnostics',
    region: 'global',
    type: 'Databook',
    description: 'Veterinary diagnostics are evolving from clinic-based testing to rapid point-of-care platforms enabling same-visit diagnosis. AI-powered imaging analysis and genomic testing are advancing companion animal and livestock disease management.',
    revenue: 7.8,
    forecast: 18.3,
    cagr: 12.9,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 3.8 }, { year: 2019, value: 4.4 }, { year: 2020, value: 4.9 },
      { year: 2021, value: 5.6 }, { year: 2022, value: 6.8 }, { year: 2023, value: 7.8 },
      { year: 2024, value: 8.9 }, { year: 2025, value: 10.2 }, { year: 2026, value: 11.8 },
      { year: 2027, value: 13.6 }, { year: 2028, value: 15.4 }, { year: 2029, value: 17.0 },
      { year: 2030, value: 18.3 },
    ],
    segments: ['Technology', 'Animal Type', 'End User', 'Region'],
    companies: [
      { name: 'IDEXX Laboratories', employees: '10,800+', hq: 'Westbrook, USA', website: 'idexx.com' },
      { name: 'Heska', employees: '900+', hq: 'Loveland, USA', website: 'heska.com' },
      { name: 'Neogen', employees: '2,100+', hq: 'Lansing, USA', website: 'neogen.com' },
    ],
    highlights: [
      'Point-of-care chemistry analyzers growing at 16% CAGR as in-clinic testing replaces lab send-outs',
      'Companion animal segment accounts for 54% of total veterinary diagnostics revenue',
      'Genomic testing for livestock breeding optimization growing rapidly in North America and Europe',
    ],
    relatedMarkets: ['Animal Vaccines Market', 'Companion Animal Health Market', 'Food Safety Testing Market'],
  },

  // ── Bulk Chemicals ───────────────────────────────────────────────────────
  {
    slug: 'industrial-gases',
    title: 'Industrial Gases',
    industry: 'Bulk Chemicals',
    subIndustry: 'Industrial Gases',
    region: 'global',
    type: 'Databook',
    description: 'Industrial gases are critical feedstocks for steel, healthcare, electronics, and food processing. Green hydrogen production is emerging as a transformative growth vector, supported by $320B in global government subsidies through 2030.',
    revenue: 108.9,
    forecast: 218.4,
    cagr: 10.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 68.4 }, { year: 2019, value: 74.2 }, { year: 2020, value: 72.8 },
      { year: 2021, value: 82.4 }, { year: 2022, value: 98.7 }, { year: 2023, value: 108.9 },
      { year: 2024, value: 120.4 }, { year: 2025, value: 133.8 }, { year: 2026, value: 148.4 },
      { year: 2027, value: 164.8 }, { year: 2028, value: 181.4 }, { year: 2029, value: 201.2 },
      { year: 2030, value: 218.4 },
    ],
    segments: ['Gas Type', 'Mode of Supply', 'Application', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'Linde', employees: '65,000+', hq: 'Guildford, UK', website: 'linde.com' },
      { name: 'Air Liquide', employees: '66,400+', hq: 'Paris, France', website: 'airliquide.com' },
      { name: 'Air Products', employees: '20,000+', hq: 'Allentown, USA', website: 'airproducts.com' },
    ],
    highlights: [
      'Linde and Air Liquide collectively hold ~48% of global industrial gases market share',
      'Green hydrogen capacity is expected to reach 600 GW by 2030, fueling industrial gas demand',
      'Medical oxygen demand grew 18% post-COVID as healthcare infrastructure investment increased',
    ],
    relatedMarkets: ['Green Hydrogen Market', 'Specialty Gases Market', 'Carbon Capture Market'],
  },
  {
    slug: 'petrochemicals',
    title: 'Petrochemicals',
    industry: 'Bulk Chemicals',
    subIndustry: 'Petrochemicals',
    region: 'global',
    type: 'Report',
    description: 'The petrochemical market spans ethylene, propylene, BTX aromatics, and their derivatives. Shifting feedstock economics, growing Asian capacity, and demand for bio-based alternatives are reshaping global trade flows.',
    revenue: 612.4,
    forecast: 1024.8,
    cagr: 7.6,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 428.4 }, { year: 2019, value: 441.2 }, { year: 2020, value: 412.8 },
      { year: 2021, value: 498.4 }, { year: 2022, value: 578.2 }, { year: 2023, value: 612.4 },
      { year: 2024, value: 664.8 }, { year: 2025, value: 718.4 }, { year: 2026, value: 778.2 },
      { year: 2027, value: 838.4 }, { year: 2028, value: 898.2 }, { year: 2029, value: 962.4 },
      { year: 2030, value: 1024.8 },
    ],
    segments: ['Product Type', 'Feedstock', 'Application', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'BASF', employees: '111,000+', hq: 'Ludwigshafen, Germany', website: 'basf.com' },
      { name: 'SABIC', employees: '33,000+', hq: 'Riyadh, Saudi Arabia', website: 'sabic.com' },
      { name: 'Dow', employees: '36,500+', hq: 'Midland, USA', website: 'dow.com' },
      { name: 'LyondellBasell', employees: '19,000+', hq: 'Houston, USA', website: 'lyondellbasell.com' },
    ],
    highlights: [
      'Ethylene remains the largest product segment with 28% of global petrochemical revenue',
      'China accounts for 42% of new petrochemical capacity additions through 2027',
      'Bio-based feedstocks expected to represent 8% of total production by 2030',
    ],
    relatedMarkets: ['Plastics Market', 'Specialty Chemicals Market', 'Fertilizers Market'],
  },

  // ── Consumer Goods ───────────────────────────────────────────────────────
  {
    slug: 'personal-care',
    title: 'Personal Care',
    industry: 'Consumer Goods',
    subIndustry: 'Personal Care',
    region: 'global',
    type: 'Report',
    description: 'The personal care market encompasses skincare, haircare, oral care, and hygiene products. Premiumization, clean beauty trends, and D2C brand proliferation are driving above-category growth in skincare and sun protection.',
    revenue: 518.2,
    forecast: 891.4,
    cagr: 8.0,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 348.4 }, { year: 2019, value: 371.2 }, { year: 2020, value: 362.8 },
      { year: 2021, value: 398.4 }, { year: 2022, value: 462.8 }, { year: 2023, value: 518.2 },
      { year: 2024, value: 562.4 }, { year: 2025, value: 612.8 }, { year: 2026, value: 668.4 },
      { year: 2027, value: 722.8 }, { year: 2028, value: 778.4 }, { year: 2029, value: 834.8 },
      { year: 2030, value: 891.4 },
    ],
    segments: ['Product Type', 'Distribution Channel', 'Gender', 'Consumer Group', 'Region'],
    companies: [
      { name: "L'Oréal", employees: '88,000+', hq: 'Clichy, France', website: 'loreal.com' },
      { name: 'Procter & Gamble', employees: '107,000+', hq: 'Cincinnati, USA', website: 'pg.com' },
      { name: 'Unilever', employees: '127,000+', hq: 'London, UK', website: 'unilever.com' },
      { name: 'Colgate-Palmolive', employees: '34,200+', hq: 'New York, USA', website: 'colgatepalmolive.com' },
    ],
    highlights: [
      'Skincare is the largest product category with 38% of total personal care revenue in 2023',
      'Clean beauty and sustainable packaging now a purchase driver for 61% of consumers',
      'Asia Pacific leads regional growth at 10.4% CAGR, driven by South Korea and India',
      'E-commerce now represents 28% of personal care sales globally, up from 12% in 2018',
    ],
    relatedMarkets: ['Beauty & Cosmetics Market', 'Fragrances Market', 'Home Care Market'],
  },
  {
    slug: 'beauty-cosmetics',
    title: 'Beauty & Cosmetics',
    industry: 'Consumer Goods',
    subIndustry: 'Beauty & Cosmetics',
    region: 'global',
    type: 'Databook',
    description: 'The beauty and cosmetics market is undergoing a structural shift driven by social commerce, influencer marketing, and ingredient transparency. Prestige skincare and makeup are outpacing mass segments as consumers trade up.',
    revenue: 287.4,
    forecast: 548.7,
    cagr: 9.6,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 178.4 }, { year: 2019, value: 192.8 }, { year: 2020, value: 178.2 },
      { year: 2021, value: 212.4 }, { year: 2022, value: 254.8 }, { year: 2023, value: 287.4 },
      { year: 2024, value: 316.8 }, { year: 2025, value: 348.4 }, { year: 2026, value: 384.2 },
      { year: 2027, value: 422.8 }, { year: 2028, value: 462.4 }, { year: 2029, value: 504.8 },
      { year: 2030, value: 548.7 },
    ],
    segments: ['Product', 'Distribution Channel', 'Gender', 'Price Range', 'Region'],
    companies: [
      { name: "L'Oréal", employees: '88,000+', hq: 'Clichy, France', website: 'loreal.com' },
      { name: 'Estée Lauder', employees: '62,000+', hq: 'New York, USA', website: 'esteelauder.com' },
      { name: 'LVMH', employees: '196,000+', hq: 'Paris, France', website: 'lvmh.com' },
      { name: 'Shiseido', employees: '33,000+', hq: 'Tokyo, Japan', website: 'shiseido.com' },
    ],
    highlights: [
      'Prestige cosmetics growing at 12.4% CAGR, nearly double the mass segment growth rate',
      'TikTok Shop driving 23% of beauty product discovery among Gen Z consumers',
      'Skincare-makeup convergence creating new "skinimalism" product category worth $18B',
    ],
    relatedMarkets: ['Personal Care Market', 'Fragrances Market', 'Men\'s Grooming Market'],
  },

  // ── Consumer Services ────────────────────────────────────────────────────
  {
    slug: 'e-commerce-market',
    title: 'E-Commerce',
    industry: 'Consumer Services',
    subIndustry: 'E-commerce',
    region: 'global',
    type: 'Report',
    description: 'Global e-commerce continues to capture share from physical retail, with social commerce, quick-commerce, and B2B platforms driving the next growth wave. Emerging market internet penetration is unlocking billions of new online shoppers.',
    revenue: 6217.8,
    forecast: 15844.3,
    cagr: 14.3,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 2841.2 }, { year: 2019, value: 3354.8 }, { year: 2020, value: 4248.4 },
      { year: 2021, value: 5211.8 }, { year: 2022, value: 5784.2 }, { year: 2023, value: 6217.8 },
      { year: 2024, value: 7121.4 }, { year: 2025, value: 8248.8 }, { year: 2026, value: 9612.4 },
      { year: 2027, value: 11128.2 }, { year: 2028, value: 12684.8 }, { year: 2029, value: 14218.4 },
      { year: 2030, value: 15844.3 },
    ],
    segments: ['Business Model', 'Product Category', 'Device', 'Payment Method', 'Region'],
    companies: [
      { name: 'Amazon', employees: '1,541,000+', hq: 'Seattle, USA', website: 'amazon.com' },
      { name: 'Alibaba', employees: '228,000+', hq: 'Hangzhou, China', website: 'alibaba.com' },
      { name: 'JD.com', employees: '608,000+', hq: 'Beijing, China', website: 'jd.com' },
      { name: 'Shopify', employees: '10,000+', hq: 'Ottawa, Canada', website: 'shopify.com' },
    ],
    highlights: [
      'China accounts for 47% of global e-commerce GMV, led by Alibaba and JD.com',
      'Social commerce GMV exceeded $1.3T in 2023, with TikTok Shop growing 500% YoY',
      'Quick-commerce (sub-30min delivery) capturing 8% of grocery e-commerce in urban markets',
    ],
    relatedMarkets: ['Digital Payments Market', 'Logistics & Fulfillment Market', 'Social Commerce Market'],
  },
  {
    slug: 'streaming-services',
    title: 'Video Streaming',
    industry: 'Consumer Services',
    subIndustry: 'Streaming',
    region: 'global',
    type: 'Databook',
    description: 'Video streaming has fundamentally displaced linear television in developed markets. Ad-supported tiers, live sports rights acquisitions, and emerging market expansion define the battleground for subscriber growth.',
    revenue: 112.4,
    forecast: 312.8,
    cagr: 15.8,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 38.4 }, { year: 2019, value: 51.2 }, { year: 2020, value: 68.4 },
      { year: 2021, value: 84.8 }, { year: 2022, value: 99.4 }, { year: 2023, value: 112.4 },
      { year: 2024, value: 132.8 }, { year: 2025, value: 158.4 }, { year: 2026, value: 188.2 },
      { year: 2027, value: 221.4 }, { year: 2028, value: 254.8 }, { year: 2029, value: 284.4 },
      { year: 2030, value: 312.8 },
    ],
    segments: ['Content Type', 'Revenue Model', 'Device', 'Region'],
    companies: [
      { name: 'Netflix', employees: '13,000+', hq: 'Los Gatos, USA', website: 'netflix.com' },
      { name: 'Disney+', employees: '225,000+', hq: 'Burbank, USA', website: 'disneyplus.com' },
      { name: 'Amazon Prime Video', employees: '1,541,000+', hq: 'Seattle, USA', website: 'primevideo.com' },
      { name: 'YouTube', employees: '182,000+', hq: 'San Bruno, USA', website: 'youtube.com' },
    ],
    highlights: [
      'Ad-supported streaming (AVOD) growing at 22% CAGR as consumers seek lower-cost options',
      'Live sports streaming rights now valued at $18B annually globally',
      'Asia Pacific adding 60M+ new subscribers per year driven by mobile-first consumption',
    ],
    relatedMarkets: ['OTT Platform Market', 'Digital Advertising Market', 'Connected TV Market'],
  },

  // ── Materials ────────────────────────────────────────────────────────────
  {
    slug: 'advanced-materials',
    title: 'Advanced Materials',
    industry: 'Materials',
    subIndustry: 'Advanced Materials',
    region: 'global',
    type: 'Report',
    description: 'Advanced materials underpin innovation across aerospace, electronics, energy, and biomedical sectors. Graphene, metamaterials, aerogels, and biomimetic materials are transitioning from lab to commercial scale production.',
    revenue: 98.4,
    forecast: 212.8,
    cagr: 11.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 56.2 }, { year: 2019, value: 63.4 }, { year: 2020, value: 67.8 },
      { year: 2021, value: 76.4 }, { year: 2022, value: 88.2 }, { year: 2023, value: 98.4 },
      { year: 2024, value: 110.8 }, { year: 2025, value: 124.4 }, { year: 2026, value: 140.2 },
      { year: 2027, value: 158.4 }, { year: 2028, value: 174.8 }, { year: 2029, value: 194.4 },
      { year: 2030, value: 212.8 },
    ],
    segments: ['Material Type', 'Application', 'End-Use Industry', 'Region'],
    companies: [
      { name: '3M', employees: '85,000+', hq: 'Saint Paul, USA', website: '3m.com' },
      { name: 'Hexcel', employees: '9,600+', hq: 'Stamford, USA', website: 'hexcel.com' },
      { name: 'Materion', employees: '3,400+', hq: 'Mayfield Heights, USA', website: 'materion.com' },
    ],
    highlights: [
      'Carbon fiber reinforced polymers growing at 14% CAGR driven by aerospace and EV lightweighting',
      'Graphene commercialization accelerating with 500+ products now in market globally',
      'Thermal interface materials demand surging with AI server and EV battery cooling requirements',
    ],
    relatedMarkets: ['Composite Materials Market', 'Nanomaterials Market', 'Coatings Market'],
  },
  {
    slug: 'composite-materials',
    title: 'Composite Materials',
    industry: 'Materials',
    subIndustry: 'Composites',
    region: 'global',
    type: 'Statistics',
    description: 'Composite materials are replacing metals across aerospace, wind energy, automotive, and construction. Carbon fiber and glass fiber composites deliver unmatched strength-to-weight ratios, enabling structural performance improvements.',
    revenue: 42.8,
    forecast: 98.4,
    cagr: 12.6,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 22.4 }, { year: 2019, value: 25.8 }, { year: 2020, value: 24.4 },
      { year: 2021, value: 28.8 }, { year: 2022, value: 36.4 }, { year: 2023, value: 42.8 },
      { year: 2024, value: 48.4 }, { year: 2025, value: 55.2 }, { year: 2026, value: 62.8 },
      { year: 2027, value: 71.4 }, { year: 2028, value: 80.8 }, { year: 2029, value: 89.4 },
      { year: 2030, value: 98.4 },
    ],
    segments: ['Fiber Type', 'Resin Type', 'Manufacturing Process', 'Application', 'Region'],
    companies: [
      { name: 'Toray Industries', employees: '50,000+', hq: 'Tokyo, Japan', website: 'toray.com' },
      { name: 'SGL Carbon', employees: '4,600+', hq: 'Wiesbaden, Germany', website: 'sglcarbon.com' },
      { name: 'Owens Corning', employees: '19,000+', hq: 'Toledo, USA', website: 'owenscorning.com' },
    ],
    highlights: [
      'Carbon fiber demand from wind turbine blades represents 28% of total composite usage',
      'Automotive composites growing at 16% CAGR as EV manufacturers target weight reduction',
      'Automated fiber placement manufacturing reducing production costs by 40%',
    ],
    relatedMarkets: ['Advanced Materials Market', 'Wind Energy Market', 'Aerospace Materials Market'],
  },

  // ── Metals & Mining ──────────────────────────────────────────────────────
  {
    slug: 'lithium-mining',
    title: 'Lithium',
    industry: 'Metals & Mining',
    subIndustry: 'Lithium',
    region: 'global',
    type: 'Report',
    description: 'Lithium is the critical mineral enabling the energy transition, with battery-grade lithium demand driven by EV and grid storage growth. Supply chain diversification and direct lithium extraction technologies are reshaping the production landscape.',
    revenue: 58.4,
    forecast: 184.8,
    cagr: 17.9,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 14.2 }, { year: 2019, value: 12.8 }, { year: 2020, value: 14.4 },
      { year: 2021, value: 24.8 }, { year: 2022, value: 78.4 }, { year: 2023, value: 58.4 },
      { year: 2024, value: 72.8 }, { year: 2025, value: 92.4 }, { year: 2026, value: 114.8 },
      { year: 2027, value: 138.4 }, { year: 2028, value: 158.2 }, { year: 2029, value: 172.4 },
      { year: 2030, value: 184.8 },
    ],
    segments: ['Product Form', 'Application', 'Source', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'Albemarle', employees: '7,400+', hq: 'Charlotte, USA', website: 'albemarle.com' },
      { name: 'SQM', employees: '5,600+', hq: 'Santiago, Chile', website: 'sqm.com' },
      { name: 'Ganfeng Lithium', employees: '18,000+', hq: 'Xinyu, China', website: 'ganfenglithium.com' },
    ],
    highlights: [
      'Chile, Australia, and Argentina hold 75% of proven global lithium reserves',
      'Battery-grade lithium carbonate accounts for 68% of demand from EV manufacturers',
      'Direct lithium extraction (DLE) technology could reduce production costs by 30%',
    ],
    relatedMarkets: ['EV Battery Market', 'Energy Storage Market', 'Cobalt Market'],
  },
  {
    slug: 'rare-earth-elements',
    title: 'Rare Earth Elements',
    industry: 'Metals & Mining',
    subIndustry: 'Rare Earth Elements',
    region: 'global',
    type: 'Databook',
    description: 'Rare earth elements are critical to permanent magnets, catalysts, and phosphors powering EVs, wind turbines, and consumer electronics. Geopolitical supply concentration in China is driving Western nations to develop alternative sources.',
    revenue: 9.8,
    forecast: 24.1,
    cagr: 13.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 4.8 }, { year: 2019, value: 5.4 }, { year: 2020, value: 5.8 },
      { year: 2021, value: 6.8 }, { year: 2022, value: 8.4 }, { year: 2023, value: 9.8 },
      { year: 2024, value: 11.2 }, { year: 2025, value: 12.9 }, { year: 2026, value: 14.9 },
      { year: 2027, value: 17.2 }, { year: 2028, value: 19.4 }, { year: 2029, value: 21.8 },
      { year: 2030, value: 24.1 },
    ],
    segments: ['Element Type', 'Application', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'MP Materials', employees: '500+', hq: 'Las Vegas, USA', website: 'mpmaterials.com' },
      { name: 'Lynas Rare Earths', employees: '900+', hq: 'Mount Walton East, Australia', website: 'lynasrareearths.com' },
      { name: 'China Northern Rare Earth', employees: '30,000+', hq: 'Baotou, China', website: 'cnre.com.cn' },
    ],
    highlights: [
      'China controls 85% of rare earth processing capacity, creating critical supply chain risk',
      'Neodymium-praseodymium (NdPr) for EV motors is the fastest-growing demand segment at 20% CAGR',
      'US Department of Defense invested $439M in domestic rare earth supply chain development',
    ],
    relatedMarkets: ['EV Motor Market', 'Wind Turbine Market', 'Critical Minerals Market'],
  },

  // ── Plastics ─────────────────────────────────────────────────────────────
  {
    slug: 'bio-based-plastics',
    title: 'Bio-Based Plastics',
    industry: 'Plastics',
    subIndustry: 'Bio-Based Plastics',
    region: 'global',
    type: 'Report',
    description: 'Bio-based and biodegradable plastics are gaining traction as brands respond to plastic regulation and consumer sustainability demands. PLA, PHA, and starch-blend technologies are reaching cost-competitive maturity.',
    revenue: 14.8,
    forecast: 48.2,
    cagr: 18.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 5.4 }, { year: 2019, value: 6.4 }, { year: 2020, value: 7.2 },
      { year: 2021, value: 8.8 }, { year: 2022, value: 11.8 }, { year: 2023, value: 14.8 },
      { year: 2024, value: 18.2 }, { year: 2025, value: 22.4 }, { year: 2026, value: 27.8 },
      { year: 2027, value: 33.8 }, { year: 2028, value: 39.4 }, { year: 2029, value: 44.2 },
      { year: 2030, value: 48.2 },
    ],
    segments: ['Material Type', 'Application', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'NatureWorks', employees: '400+', hq: 'Plymouth, USA', website: 'natureworksllc.com' },
      { name: 'Total Corbion', employees: '700+', hq: 'Gorinchem, Netherlands', website: 'total-corbion.com' },
      { name: 'Danimer Scientific', employees: '400+', hq: 'Bainbridge, USA', website: 'danimerscientific.com' },
    ],
    highlights: [
      'EU Single-Use Plastics Directive driving mandatory 30% bio-based content in packaging by 2030',
      'PLA (polylactic acid) dominates with 46% of bio-plastics production volume',
      'Food & beverage packaging accounts for 48% of bio-plastics demand',
    ],
    relatedMarkets: ['Sustainable Packaging Market', 'Biopolymers Market', 'Recycled Plastics Market'],
  },
  {
    slug: 'engineering-plastics',
    title: 'Engineering Plastics',
    industry: 'Plastics',
    subIndustry: 'Engineering Plastics',
    region: 'global',
    type: 'Databook',
    description: 'Engineering plastics replace metals in automotive, electronics, and industrial applications where high performance under stress and temperature is required. Lightweighting mandates in EVs and electronics miniaturization are key demand drivers.',
    revenue: 112.4,
    forecast: 218.7,
    cagr: 9.9,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 68.4 }, { year: 2019, value: 74.2 }, { year: 2020, value: 72.8 },
      { year: 2021, value: 82.4 }, { year: 2022, value: 98.8 }, { year: 2023, value: 112.4 },
      { year: 2024, value: 124.8 }, { year: 2025, value: 138.4 }, { year: 2026, value: 153.8 },
      { year: 2027, value: 170.4 }, { year: 2028, value: 187.2 }, { year: 2029, value: 202.8 },
      { year: 2030, value: 218.7 },
    ],
    segments: ['Material Type', 'Application', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'BASF', employees: '111,000+', hq: 'Ludwigshafen, Germany', website: 'basf.com' },
      { name: 'DuPont', employees: '24,000+', hq: 'Wilmington, USA', website: 'dupont.com' },
      { name: 'SABIC', employees: '33,000+', hq: 'Riyadh, Saudi Arabia', website: 'sabic.com' },
      { name: 'Covestro', employees: '17,500+', hq: 'Leverkusen, Germany', website: 'covestro.com' },
    ],
    highlights: [
      'Polyamide (PA) and polycarbonate (PC) together account for 42% of engineering plastics volume',
      'Automotive sector consumes 38% of engineering plastics, driven by EV structural components',
      'High-performance thermoplastics growing at 14% CAGR in electronics applications',
    ],
    relatedMarkets: ['Automotive Materials Market', 'Electronics Plastics Market', 'Composites Market'],
  },

  // ── Sexual Health ────────────────────────────────────────────────────────
  {
    slug: 'contraceptives-market',
    title: 'Contraceptives',
    industry: 'Sexual Health',
    subIndustry: 'Contraceptives',
    region: 'global',
    type: 'Report',
    description: 'The contraceptives market is evolving with long-acting reversible contraceptive (LARC) adoption, male contraceptive development, and digital cycle-tracking platforms. Telehealth prescription services are expanding access in underserved markets.',
    revenue: 24.8,
    forecast: 41.2,
    cagr: 7.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 16.4 }, { year: 2019, value: 17.8 }, { year: 2020, value: 18.4 },
      { year: 2021, value: 20.2 }, { year: 2022, value: 22.8 }, { year: 2023, value: 24.8 },
      { year: 2024, value: 26.7 }, { year: 2025, value: 28.8 }, { year: 2026, value: 31.1 },
      { year: 2027, value: 33.4 }, { year: 2028, value: 35.8 }, { year: 2029, value: 38.4 },
      { year: 2030, value: 41.2 },
    ],
    segments: ['Product Type', 'Gender', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Bayer', employees: '100,000+', hq: 'Leverkusen, Germany', website: 'bayer.com' },
      { name: 'Pfizer', employees: '83,000+', hq: 'New York, USA', website: 'pfizer.com' },
      { name: 'Merck & Co.', employees: '68,000+', hq: 'Rahway, USA', website: 'merck.com' },
    ],
    highlights: [
      'Intrauterine devices (IUDs) are the fastest-growing product type at 9.2% CAGR',
      'Online pharmacy channels now account for 22% of OTC contraceptive purchases',
      'Male contraceptive R&D pipeline includes 12 active clinical programs as of 2024',
    ],
    relatedMarkets: ['Fertility Services Market', 'Women\'s Health Market', 'STI Diagnostics Market'],
  },
  {
    slug: 'fertility-services',
    title: 'Fertility Services',
    industry: 'Sexual Health',
    subIndustry: 'Fertility',
    region: 'global',
    type: 'Databook',
    description: 'Fertility services are expanding as delayed childbearing, rising infertility rates, and increasing social acceptance drive demand. IVF cycle volumes are growing 10%+ annually, with AI-assisted embryo selection improving success rates.',
    revenue: 8.2,
    forecast: 21.4,
    cagr: 14.8,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 3.4 }, { year: 2019, value: 4.0 }, { year: 2020, value: 4.2 },
      { year: 2021, value: 5.1 }, { year: 2022, value: 6.8 }, { year: 2023, value: 8.2 },
      { year: 2024, value: 9.6 }, { year: 2025, value: 11.2 }, { year: 2026, value: 13.1 },
      { year: 2027, value: 15.2 }, { year: 2028, value: 17.4 }, { year: 2029, value: 19.4 },
      { year: 2030, value: 21.4 },
    ],
    segments: ['Service Type', 'Cycle Type', 'End User', 'Region'],
    companies: [
      { name: 'CooperSurgical', employees: '13,000+', hq: 'Trumbull, USA', website: 'coopersurgical.com' },
      { name: 'Vitrolife', employees: '1,800+', hq: 'Gothenburg, Sweden', website: 'vitrolife.com' },
      { name: 'Ferring Pharmaceuticals', employees: '7,000+', hq: 'Saint-Prex, Switzerland', website: 'ferring.com' },
    ],
    highlights: [
      'Global IVF cycles surpassed 3 million per year in 2023, with Europe performing 40% of cycles',
      'AI-guided embryo selection improving IVF success rates by up to 25% in clinical studies',
      'Employer-sponsored fertility benefits now cover 42% of Fortune 500 company employees',
    ],
    relatedMarkets: ['Contraceptives Market', 'Reproductive Genetics Market', 'Women\'s Health Market'],
  },

  // ── Specialty Chemicals ──────────────────────────────────────────────────
  {
    slug: 'agrochemicals-market',
    title: 'Agrochemicals',
    industry: 'Specialty Chemicals',
    subIndustry: 'Agrochemicals',
    region: 'global',
    type: 'Report',
    description: 'The agrochemicals market encompasses crop protection chemicals, fertilizers, and plant growth regulators. Precision agriculture, biological crop protection, and gene editing are redefining the industry\'s innovation roadmap.',
    revenue: 248.4,
    forecast: 412.8,
    cagr: 7.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 178.4 }, { year: 2019, value: 188.2 }, { year: 2020, value: 194.8 },
      { year: 2021, value: 212.4 }, { year: 2022, value: 234.8 }, { year: 2023, value: 248.4 },
      { year: 2024, value: 268.8 }, { year: 2025, value: 291.4 }, { year: 2026, value: 314.8 },
      { year: 2027, value: 338.4 }, { year: 2028, value: 362.8 }, { year: 2029, value: 388.4 },
      { year: 2030, value: 412.8 },
    ],
    segments: ['Product Type', 'Crop Type', 'Mode of Application', 'Region'],
    companies: [
      { name: 'Syngenta', employees: '48,000+', hq: 'Basel, Switzerland', website: 'syngenta.com' },
      { name: 'Bayer Crop Science', employees: '100,000+', hq: 'Monheim, Germany', website: 'bayer.com' },
      { name: 'BASF Agricultural Solutions', employees: '111,000+', hq: 'Ludwigshafen, Germany', website: 'basf.com' },
      { name: 'Corteva', employees: '21,000+', hq: 'Indianapolis, USA', website: 'corteva.com' },
    ],
    highlights: [
      'Herbicides represent the largest product segment with 44% of global agrochemical revenue',
      'Biological crop protection growing at 16% CAGR as regulatory pressure reduces synthetic options',
      'Asia Pacific consumes 45% of global agrochemicals, led by India and China',
    ],
    relatedMarkets: ['Fertilizers Market', 'Precision Agriculture Market', 'Biopesticides Market'],
  },
  {
    slug: 'water-treatment-chemicals',
    title: 'Water Treatment Chemicals',
    industry: 'Specialty Chemicals',
    subIndustry: 'Water Treatment',
    region: 'global',
    type: 'Statistics',
    description: 'Water treatment chemicals ensure safe industrial and municipal water through coagulation, disinfection, and scale control. Tightening environmental regulations and water scarcity are driving adoption of advanced treatment solutions.',
    revenue: 38.4,
    forecast: 78.2,
    cagr: 10.8,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 22.4 }, { year: 2019, value: 24.8 }, { year: 2020, value: 26.2 },
      { year: 2021, value: 28.8 }, { year: 2022, value: 34.4 }, { year: 2023, value: 38.4 },
      { year: 2024, value: 42.8 }, { year: 2025, value: 47.8 }, { year: 2026, value: 53.4 },
      { year: 2027, value: 59.8 }, { year: 2028, value: 66.4 }, { year: 2029, value: 72.8 },
      { year: 2030, value: 78.2 },
    ],
    segments: ['Product Type', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'Veolia', employees: '213,000+', hq: 'Aubervilliers, France', website: 'veolia.com' },
      { name: 'Ecolab', employees: '48,000+', hq: 'Saint Paul, USA', website: 'ecolab.com' },
      { name: 'Kemira', employees: '5,000+', hq: 'Helsinki, Finland', website: 'kemira.com' },
    ],
    highlights: [
      'Municipal water treatment accounts for 38% of total water treatment chemical demand',
      'PFAS remediation chemicals emerging as a high-growth segment driven by US EPA regulations',
      'Membrane technology reducing chemical consumption by 30% in desalination applications',
    ],
    relatedMarkets: ['Industrial Water Treatment Market', 'Wastewater Treatment Market', 'Desalination Market'],
  },

  // ── MedTech (additional) ─────────────────────────────────────────────────
  {
    slug: 'medical-imaging',
    title: 'Medical Imaging',
    industry: 'MedTech',
    subIndustry: 'Imaging Systems',
    region: 'global',
    type: 'Report',
    description: 'Medical imaging systems — including MRI, CT, ultrasound, and X-ray — are the diagnostic backbone of modern healthcare. AI-powered image analysis and portable imaging devices are extending diagnostics beyond hospital settings.',
    revenue: 42.8,
    forecast: 89.4,
    cagr: 11.1,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 24.2 }, { year: 2019, value: 27.1 }, { year: 2020, value: 28.4 },
      { year: 2021, value: 32.8 }, { year: 2022, value: 38.4 }, { year: 2023, value: 42.8 },
      { year: 2024, value: 47.9 }, { year: 2025, value: 53.8 }, { year: 2026, value: 60.4 },
      { year: 2027, value: 67.8 }, { year: 2028, value: 75.4 }, { year: 2029, value: 82.8 },
      { year: 2030, value: 89.4 },
    ],
    segments: ['Modality', 'Application', 'End User', 'Region'],
    companies: [
      { name: 'GE HealthCare', employees: '51,000+', hq: 'Chicago, USA', website: 'gehealthcare.com' },
      { name: 'Siemens Healthineers', employees: '69,500+', hq: 'Erlangen, Germany', website: 'siemens-healthineers.com' },
      { name: 'Philips Healthcare', employees: '77,000+', hq: 'Amsterdam, Netherlands', website: 'philips.com' },
      { name: 'Canon Medical Systems', employees: '25,000+', hq: 'Otawara, Japan', website: 'global.medical.canon' },
    ],
    highlights: [
      'MRI systems hold 33% of medical imaging revenue, driven by neurological and musculoskeletal imaging',
      'AI-powered radiology tools reduce image reading time by 45% and improve diagnostic accuracy',
      'Point-of-care ultrasound growing at 16% CAGR for bedside and emergency diagnostics',
    ],
    relatedMarkets: ['Radiology AI Market', 'Surgical Robotics Market', 'Orthopedic Implants Market'],
  },
  {
    slug: 'orthopedic-implants',
    title: 'Orthopedic Implants',
    industry: 'MedTech',
    subIndustry: 'Orthopedics',
    region: 'global',
    type: 'Statistics',
    description: 'Orthopedic implants address joint, spine, and bone injuries in an aging population with rising obesity rates. 3D-printed patient-specific implants, robotic-assisted surgery, and bioresorbable materials are driving the next product generation.',
    revenue: 52.4,
    forecast: 108.8,
    cagr: 11.0,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 30.2 }, { year: 2019, value: 33.4 }, { year: 2020, value: 30.8 },
      { year: 2021, value: 36.4 }, { year: 2022, value: 46.8 }, { year: 2023, value: 52.4 },
      { year: 2024, value: 58.2 }, { year: 2025, value: 64.8 }, { year: 2026, value: 72.4 },
      { year: 2027, value: 80.8 }, { year: 2028, value: 89.4 }, { year: 2029, value: 98.8 },
      { year: 2030, value: 108.8 },
    ],
    segments: ['Product Type', 'Material', 'End User', 'Region'],
    companies: [
      { name: 'Zimmer Biomet', employees: '20,000+', hq: 'Warsaw, USA', website: 'zimmerbiomet.com' },
      { name: 'Stryker', employees: '51,000+', hq: 'Kalamazoo, USA', website: 'stryker.com' },
      { name: 'DePuy Synthes (J&J)', employees: '152,000+', hq: 'Raynham, USA', website: 'depuysynthes.com' },
      { name: 'Smith+Nephew', employees: '18,000+', hq: 'London, UK', website: 'smith-nephew.com' },
    ],
    highlights: [
      'Knee implants are the largest segment representing 38% of total orthopedic implant revenue',
      'Robotic-assisted orthopedic procedures now account for 22% of hip and knee replacements in the US',
      '3D-printed orthopedic implants market growing at 18% CAGR with 2,000+ FDA-cleared designs',
    ],
    relatedMarkets: ['Surgical Robotics Market', 'Medical Imaging Market', 'Spine Surgery Market'],
  },

  // ── Packaging (additional) ───────────────────────────────────────────────
  {
    slug: 'sustainable-packaging',
    title: 'Sustainable Packaging',
    industry: 'Packaging',
    subIndustry: 'Sustainable Packaging',
    region: 'global',
    type: 'Report',
    description: 'Sustainable packaging is moving from niche preference to mainstream mandate as brands respond to Extended Producer Responsibility (EPR) legislation and consumer-driven sustainability expectations. Recyclable, compostable, and reusable formats are scaling rapidly.',
    revenue: 312.8,
    forecast: 712.4,
    cagr: 12.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 158.4 }, { year: 2019, value: 181.2 }, { year: 2020, value: 198.4 },
      { year: 2021, value: 224.8 }, { year: 2022, value: 278.4 }, { year: 2023, value: 312.8 },
      { year: 2024, value: 354.2 }, { year: 2025, value: 401.8 }, { year: 2026, value: 454.2 },
      { year: 2027, value: 511.8 }, { year: 2028, value: 572.4 }, { year: 2029, value: 641.8 },
      { year: 2030, value: 712.4 },
    ],
    segments: ['Material', 'Format', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'Amcor', employees: '44,000+', hq: 'Zurich, Switzerland', website: 'amcor.com' },
      { name: 'Sealed Air', employees: '17,000+', hq: 'Charlotte, USA', website: 'sealedair.com' },
      { name: 'DS Smith', employees: '30,000+', hq: 'London, UK', website: 'dssmith.com' },
      { name: 'Smurfit Kappa', employees: '47,000+', hq: 'Dublin, Ireland', website: 'smurfitkappa.com' },
    ],
    highlights: [
      'Recycled content packaging demand growing at 18% CAGR driven by brand sustainability pledges',
      'EU Packaging and Packaging Waste Regulation mandating 70% recycling rate by 2030',
      'Paper-based packaging replacing plastics in foodservice at 14% annual growth rate',
    ],
    relatedMarkets: ['Pharmaceutical Packaging Market', 'Smart Packaging Market', 'Bio-Based Plastics Market'],
  },

  // ── Pharmaceuticals (additional) ─────────────────────────────────────────
  {
    slug: 'generic-drugs',
    title: 'Generic Drugs',
    industry: 'Pharmaceuticals',
    subIndustry: 'Generic Drugs',
    region: 'global',
    type: 'Databook',
    description: 'The generic drugs market is structurally driven by patent cliffs, government cost-containment policies, and expanding biosimilar pipelines. Over $250B in branded drug revenue faces patent expiry through 2030, fueling generic opportunity.',
    revenue: 487.2,
    forecast: 912.4,
    cagr: 9.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 312.4 }, { year: 2019, value: 338.8 }, { year: 2020, value: 368.4 },
      { year: 2021, value: 398.2 }, { year: 2022, value: 444.8 }, { year: 2023, value: 487.2 },
      { year: 2024, value: 534.8 }, { year: 2025, value: 587.4 }, { year: 2026, value: 644.8 },
      { year: 2027, value: 708.4 }, { year: 2028, value: 778.2 }, { year: 2029, value: 844.8 },
      { year: 2030, value: 912.4 },
    ],
    segments: ['Product Type', 'Therapeutic Area', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Teva Pharmaceuticals', employees: '37,000+', hq: 'Tel Aviv, Israel', website: 'tevapharm.com' },
      { name: 'Viatris', employees: '37,000+', hq: 'Canonsburg, USA', website: 'viatris.com' },
      { name: 'Sun Pharma', employees: '33,000+', hq: 'Mumbai, India', website: 'sunpharma.com' },
      { name: 'Dr. Reddy\'s Laboratories', employees: '24,000+', hq: 'Hyderabad, India', website: 'drreddys.com' },
    ],
    highlights: [
      'India supplies 40% of global generic drug exports by volume, led by US and EU markets',
      'Biosimilars represent the fastest-growing generic segment at 26% CAGR through 2030',
      '$250B+ in branded drug revenue facing patent expiry between 2024 and 2030',
    ],
    relatedMarkets: ['Oncology Drugs Market', 'Contract Manufacturing Market', 'Biosimilars Market'],
  },
  {
    slug: 'cardiovascular-drugs',
    title: 'Cardiovascular Drugs',
    industry: 'Pharmaceuticals',
    subIndustry: 'Cardiovascular',
    region: 'global',
    type: 'Report',
    description: 'Cardiovascular disease remains the world\'s leading cause of death, sustaining strong drug market demand. GLP-1 agonists proven weight-reduction effects on cardiovascular risk are creating a new treatment paradigm for heart failure and risk prevention.',
    revenue: 182.4,
    forecast: 298.8,
    cagr: 7.3,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 118.4 }, { year: 2019, value: 128.8 }, { year: 2020, value: 134.4 },
      { year: 2021, value: 148.2 }, { year: 2022, value: 168.4 }, { year: 2023, value: 182.4 },
      { year: 2024, value: 197.8 }, { year: 2025, value: 214.4 }, { year: 2026, value: 232.8 },
      { year: 2027, value: 251.4 }, { year: 2028, value: 268.8 }, { year: 2029, value: 284.4 },
      { year: 2030, value: 298.8 },
    ],
    segments: ['Drug Class', 'Indication', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'AstraZeneca', employees: '83,000+', hq: 'Cambridge, UK', website: 'astrazeneca.com' },
      { name: 'Novartis', employees: '108,000+', hq: 'Basel, Switzerland', website: 'novartis.com' },
      { name: 'Pfizer', employees: '83,000+', hq: 'New York, USA', website: 'pfizer.com' },
      { name: 'Bristol-Myers Squibb', employees: '32,200+', hq: 'New York, USA', website: 'bms.com' },
    ],
    highlights: [
      'SGLT2 inhibitors and GLP-1 agonists are transforming cardiovascular risk reduction with proven mortality benefits',
      'Heart failure is the fastest-growing cardiovascular indication at 9.4% CAGR',
      'mRNA lipid nanoparticle technology being developed for cardiovascular vaccine applications',
    ],
    relatedMarkets: ['Oncology Drugs Market', 'Diabetes Drugs Market', 'Anti-hypertensives Market'],
  },

  // ── Financial Services (additional) ──────────────────────────────────────
  {
    slug: 'insurtech',
    title: 'InsurTech',
    industry: 'Financial Services',
    subIndustry: 'Insurance',
    region: 'global',
    type: 'Report',
    description: 'InsurTech is disrupting traditional insurance underwriting, claims processing, and distribution through AI, IoT telematics, and embedded insurance APIs. Usage-based insurance and parametric products are gaining mainstream adoption.',
    revenue: 48.3,
    forecast: 198.4,
    cagr: 22.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 9.4 }, { year: 2019, value: 14.2 }, { year: 2020, value: 18.8 },
      { year: 2021, value: 26.4 }, { year: 2022, value: 38.2 }, { year: 2023, value: 48.3 },
      { year: 2024, value: 62.8 }, { year: 2025, value: 81.4 }, { year: 2026, value: 104.8 },
      { year: 2027, value: 130.4 }, { year: 2028, value: 154.8 }, { year: 2029, value: 176.4 },
      { year: 2030, value: 198.4 },
    ],
    segments: ['Insurance Line', 'Technology', 'End User', 'Region'],
    companies: [
      { name: 'Lemonade', employees: '1,400+', hq: 'New York, USA', website: 'lemonade.com' },
      { name: 'Root Insurance', employees: '1,200+', hq: 'Columbus, USA', website: 'joinroot.com' },
      { name: 'Oscar Health', employees: '3,000+', hq: 'New York, USA', website: 'hioscar.com' },
    ],
    highlights: [
      'Usage-based auto insurance (UBI) penetration reached 22% of US auto policies in 2023',
      'AI-powered claims automation reducing processing time from days to minutes',
      'Embedded insurance APIs integrating coverage into e-commerce and travel booking flows',
    ],
    relatedMarkets: ['Fintech Market', 'Digital Payments Market', 'RegTech Market'],
  },
  {
    slug: 'digital-payments',
    title: 'Digital Payments',
    industry: 'Financial Services',
    subIndustry: 'Payments',
    region: 'global',
    type: 'Databook',
    description: 'Digital payments infrastructure underpins the global economy as cash usage declines and real-time payment rails proliferate. CBDC pilots, account-to-account payments, and cross-border remittance platforms are reshaping payment flows.',
    revenue: 2984.2,
    forecast: 8618.4,
    cagr: 16.4,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 1248.4 }, { year: 2019, value: 1548.2 }, { year: 2020, value: 1984.8 },
      { year: 2021, value: 2348.4 }, { year: 2022, value: 2714.8 }, { year: 2023, value: 2984.2 },
      { year: 2024, value: 3548.4 }, { year: 2025, value: 4248.8 }, { year: 2026, value: 5084.4 },
      { year: 2027, value: 6084.8 }, { year: 2028, value: 7048.4 }, { year: 2029, value: 7848.8 },
      { year: 2030, value: 8618.4 },
    ],
    segments: ['Payment Method', 'Transaction Type', 'End-Use Vertical', 'Region'],
    companies: [
      { name: 'Visa', employees: '26,500+', hq: 'Foster City, USA', website: 'visa.com' },
      { name: 'Mastercard', employees: '29,900+', hq: 'Purchase, USA', website: 'mastercard.com' },
      { name: 'PayPal', employees: '29,900+', hq: 'San Jose, USA', website: 'paypal.com' },
      { name: 'Adyen', employees: '3,700+', hq: 'Amsterdam, Netherlands', website: 'adyen.com' },
    ],
    highlights: [
      'Real-time payments transaction volume grew 65% YoY in 2023 driven by UPI, FedNow, and Pix adoption',
      'Cross-border payment fees declining 40% as stablecoin and CBDC rails gain traction',
      'Mobile wallet penetration reached 62% of internet users globally by end-2023',
    ],
    relatedMarkets: ['Fintech Market', 'InsurTech Market', 'Cryptocurrency Market'],
  },

  // ── Food Beverages & Tobacco (additional) ────────────────────────────────
  {
    slug: 'functional-food',
    title: 'Functional Food & Beverages',
    industry: 'Food Beverages & Tobacco',
    subIndustry: 'Functional Food',
    region: 'global',
    type: 'Report',
    description: 'Functional food and beverages deliver measurable health benefits beyond basic nutrition. Gut health, immunity, and cognitive performance claims are driving innovation in fortified foods, probiotic beverages, and adaptogens.',
    revenue: 312.4,
    forecast: 712.4,
    cagr: 12.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 168.4 }, { year: 2019, value: 192.8 }, { year: 2020, value: 228.4 },
      { year: 2021, value: 258.2 }, { year: 2022, value: 284.8 }, { year: 2023, value: 312.4 },
      { year: 2024, value: 354.8 }, { year: 2025, value: 402.4 }, { year: 2026, value: 455.8 },
      { year: 2027, value: 514.4 }, { year: 2028, value: 578.8 }, { year: 2029, value: 644.4 },
      { year: 2030, value: 712.4 },
    ],
    segments: ['Product Type', 'Ingredient', 'Distribution Channel', 'Consumer Group', 'Region'],
    companies: [
      { name: 'Nestlé', employees: '275,000+', hq: 'Vevey, Switzerland', website: 'nestle.com' },
      { name: 'Danone', employees: '98,000+', hq: 'Paris, France', website: 'danone.com' },
      { name: 'PepsiCo', employees: '315,000+', hq: 'Purchase, USA', website: 'pepsico.com' },
      { name: 'Kellanova', employees: '23,000+', hq: 'Battle Creek, USA', website: 'kellanova.com' },
    ],
    highlights: [
      'Gut health products (prebiotics, probiotics, postbiotics) is the fastest-growing claim at 18% CAGR',
      'Functional beverages outperforming food formats, now representing 44% of functional category revenue',
      'Clean-label functional products account for 62% of new product launches in the category',
    ],
    relatedMarkets: ['Plant-Based Food Market', 'Dietary Supplements Market', 'Probiotic Market'],
  },
  {
    slug: 'beverages-market',
    title: 'Beverages',
    industry: 'Food Beverages & Tobacco',
    subIndustry: 'Beverages',
    region: 'global',
    type: 'Statistics',
    description: 'The global beverages market spans carbonated soft drinks, energy drinks, bottled water, juices, coffee, tea, and alcoholic beverages. Health-conscious reformulation, premium positioning, and ready-to-drink formats are shifting category dynamics.',
    revenue: 1842.4,
    forecast: 3124.8,
    cagr: 7.8,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 1248.4 }, { year: 2019, value: 1348.2 }, { year: 2020, value: 1298.4 },
      { year: 2021, value: 1448.8 }, { year: 2022, value: 1648.4 }, { year: 2023, value: 1842.4 },
      { year: 2024, value: 1984.8 }, { year: 2025, value: 2148.4 }, { year: 2026, value: 2324.8 },
      { year: 2027, value: 2514.4 }, { year: 2028, value: 2714.8 }, { year: 2029, value: 2924.4 },
      { year: 2030, value: 3124.8 },
    ],
    segments: ['Product Type', 'Packaging', 'Distribution Channel', 'Region'],
    companies: [
      { name: 'Coca-Cola', employees: '79,000+', hq: 'Atlanta, USA', website: 'coca-colacompany.com' },
      { name: 'PepsiCo', employees: '315,000+', hq: 'Purchase, USA', website: 'pepsico.com' },
      { name: 'Anheuser-Busch InBev', employees: '169,000+', hq: 'Leuven, Belgium', website: 'ab-inbev.com' },
      { name: 'Nestlé', employees: '275,000+', hq: 'Vevey, Switzerland', website: 'nestle.com' },
    ],
    highlights: [
      'Energy drinks are the fastest-growing segment at 10.8% CAGR driven by Gen Z and active lifestyle consumers',
      'Zero-sugar and low-calorie variants now represent 38% of total soft drink launches',
      'Ready-to-drink coffee growing at 12.4% CAGR as on-the-go consumption normalizes',
    ],
    relatedMarkets: ['Functional Food Market', 'Plant-Based Food Market', 'Alcohol Market'],
  },

  // ── Semiconductor (additional) ───────────────────────────────────────────
  {
    slug: 'ai-chips',
    title: 'AI Chips',
    industry: 'Semiconductor',
    subIndustry: 'Logic Chips',
    region: 'global',
    type: 'Report',
    description: 'AI chips — including GPUs, TPUs, NPUs, and custom ASICs — are the computational foundation of the generative AI revolution. Hyperscaler capex cycles, edge AI deployment, and sovereign AI programs are creating exceptional demand momentum.',
    revenue: 128.4,
    forecast: 812.4,
    cagr: 30.1,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 8.4 }, { year: 2019, value: 12.8 }, { year: 2020, value: 18.4 },
      { year: 2021, value: 34.8 }, { year: 2022, value: 78.4 }, { year: 2023, value: 128.4 },
      { year: 2024, value: 218.4 }, { year: 2025, value: 318.8 }, { year: 2026, value: 428.4 },
      { year: 2027, value: 548.2 }, { year: 2028, value: 648.4 }, { year: 2029, value: 738.8 },
      { year: 2030, value: 812.4 },
    ],
    segments: ['Chip Type', 'Architecture', 'Deployment', 'Application', 'Region'],
    companies: [
      { name: 'NVIDIA', employees: '29,600+', hq: 'Santa Clara, USA', website: 'nvidia.com' },
      { name: 'AMD', employees: '26,000+', hq: 'Santa Clara, USA', website: 'amd.com' },
      { name: 'Google (TPU)', employees: '182,000+', hq: 'Mountain View, USA', website: 'cloud.google.com/tpu' },
      { name: 'Intel', employees: '120,000+', hq: 'Santa Clara, USA', website: 'intel.com' },
    ],
    highlights: [
      'NVIDIA holds 80% of AI training chip market with H100 and H200 GPU series',
      'Custom ASICs from hyperscalers (Google TPU, AWS Trainium) growing at 42% CAGR',
      'Edge AI chip deployment surpassing cloud AI chips in unit volume for the first time in 2025',
    ],
    relatedMarkets: ['Semiconductor Market', 'Cloud Computing Market', 'AI Infrastructure Market'],
  },
  {
    slug: 'power-semiconductors',
    title: 'Power Semiconductors',
    industry: 'Semiconductor',
    subIndustry: 'Power Semiconductors',
    region: 'global',
    type: 'Databook',
    description: 'Power semiconductors — including MOSFETs, IGBTs, and wide-bandgap devices (SiC, GaN) — control electrical power conversion in EVs, renewable energy, and industrial systems. SiC device adoption in EV inverters is transforming the competitive landscape.',
    revenue: 54.8,
    forecast: 138.4,
    cagr: 14.2,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 24.4 }, { year: 2019, value: 26.8 }, { year: 2020, value: 28.4 },
      { year: 2021, value: 34.2 }, { year: 2022, value: 46.8 }, { year: 2023, value: 54.8 },
      { year: 2024, value: 63.8 }, { year: 2025, value: 74.4 }, { year: 2026, value: 87.2 },
      { year: 2027, value: 101.4 }, { year: 2028, value: 114.8 }, { year: 2029, value: 127.4 },
      { year: 2030, value: 138.4 },
    ],
    segments: ['Device Type', 'Material', 'Application', 'End-Use Industry', 'Region'],
    companies: [
      { name: 'Infineon Technologies', employees: '56,000+', hq: 'Munich, Germany', website: 'infineon.com' },
      { name: 'ON Semiconductor', employees: '34,000+', hq: 'Scottsdale, USA', website: 'onsemi.com' },
      { name: 'STMicroelectronics', employees: '50,000+', hq: 'Geneva, Switzerland', website: 'st.com' },
      { name: 'Wolfspeed', employees: '4,400+', hq: 'Durham, USA', website: 'wolfspeed.com' },
    ],
    highlights: [
      'Silicon carbide (SiC) devices growing at 28% CAGR as EV manufacturers transition from IGBT to SiC inverters',
      'Gallium nitride (GaN) capturing 18% of power converter market for consumer electronics',
      'IGBT modules remain dominant in industrial drives at 44% of total power semiconductor revenue',
    ],
    relatedMarkets: ['Semiconductor Market', 'EV Battery Market', 'Solar Inverter Market'],
  },
]
