export const industries = [
  { id: 'aerospace', name: 'Aerospace & Defence', subIndustries: ['Commercial Aviation', 'Defense Systems', 'Space Technology', 'Drones & UAVs', 'Satellites'] },
  { id: 'animal-health', name: 'Animal Health', subIndustries: ['Vaccines', 'Diagnostics', 'Feed Additives', 'Companion Animal', 'Livestock'] },
  { id: 'automotive', name: 'Automotive & Transportation', subIndustries: ['Electric Vehicles', 'Autonomous Vehicles', 'Fleet Management', 'Telematics', 'Automotive Parts'] },
  { id: 'biotech', name: 'Biotechnology', subIndustries: ['Monoclonal Antibodies', 'Gene Therapy', 'Cell Therapy', 'Bioinformatics', 'Synthetic Biology', 'Bioprocessing'] },
  { id: 'bulk-chemicals', name: 'Bulk Chemicals', subIndustries: ['Industrial Gases', 'Petrochemicals', 'Fertilizers', 'Chlor-Alkali', 'Acids & Bases'] },
  { id: 'clinical-diagnostics', name: 'Clinical Diagnostics', subIndustries: ['Molecular Diagnostics', 'Point-of-Care Testing', 'Immunoassays', 'Histology', 'Flow Cytometry'] },
  { id: 'consumer-goods', name: 'Consumer Goods', subIndustries: ['Personal Care', 'Home Care', 'Beauty & Cosmetics', 'Apparel', 'Electronics'] },
  { id: 'consumer-services', name: 'Consumer Services', subIndustries: ['E-commerce', 'Streaming', 'Travel & Tourism', 'Food Delivery', 'EdTech'] },
  { id: 'energy', name: 'Energy & Power', subIndustries: ['Solar Energy', 'Wind Energy', 'Energy Storage', 'Oil & Gas', 'Smart Grid'] },
  { id: 'financial-services', name: 'Financial Services', subIndustries: ['Fintech', 'Banking', 'Insurance', 'Asset Management', 'Payments'] },
  { id: 'food-beverages', name: 'Food Beverages & Tobacco', subIndustries: ['Functional Food', 'Plant-Based', 'Beverages', 'Dairy', 'Tobacco Alternatives'] },
  { id: 'healthcare', name: 'Healthcare', subIndustries: ['Digital Health', 'Hospital Management', 'Telehealth', 'Wearables', 'Health IT'] },
  { id: 'materials', name: 'Materials', subIndustries: ['Advanced Materials', 'Composites', 'Ceramics', 'Coatings', 'Adhesives'] },
  { id: 'medtech', name: 'MedTech', subIndustries: ['Surgical Robotics', 'Imaging Systems', 'Implants', 'Wound Care', 'Orthopedics'] },
  { id: 'metals-mining', name: 'Metals & Mining', subIndustries: ['Rare Earth Elements', 'Steel', 'Aluminum', 'Copper', 'Lithium'] },
  { id: 'nutrition', name: 'Nutrition', subIndustries: ['Sports Nutrition', 'Dietary Supplements', 'Infant Nutrition', 'Clinical Nutrition', 'Probiotics'] },
  { id: 'packaging', name: 'Packaging', subIndustries: ['Flexible Packaging', 'Rigid Plastics', 'Sustainable Packaging', 'Smart Packaging', 'Labels'] },
  { id: 'pharma', name: 'Pharmaceuticals', subIndustries: ['Oncology', 'CNS', 'Cardiovascular', 'Generic Drugs', 'Contract Manufacturing'] },
  { id: 'plastics', name: 'Plastics', subIndustries: ['Engineering Plastics', 'Bio-Based Plastics', 'Recycled Plastics', 'Films', 'Foams'] },
  { id: 'semiconductor', name: 'Semiconductor', subIndustries: ['Memory Chips', 'Logic Chips', 'Power Semiconductors', 'Sensors', 'Photonics'] },
  { id: 'sexual-health', name: 'Sexual Health', subIndustries: ['Contraceptives', 'STI Testing', 'Fertility', 'ED Treatment', 'Sex Wellness'] },
  { id: 'specialty-chemicals', name: 'Specialty Chemicals', subIndustries: ['Electronic Chemicals', 'Agrochemicals', 'Construction Chemicals', 'Water Treatment', 'Surfactants'] },
  { id: 'telecom', name: 'Telecom & Technology', subIndustries: ['5G', 'Cloud Computing', 'Cybersecurity', 'IoT', 'AI & ML', 'Quantum Computing'] },
]

export const markets = [
  {
    slug: 'monoclonal-antibodies',
    title: 'Monoclonal Antibodies',
    industry: 'Biotechnology',
    subIndustry: 'Monoclonal Antibodies',
    region: 'global',
    description: 'The global monoclonal antibodies market is witnessing significant growth driven by rising prevalence of chronic diseases and cancer. Advanced biologics manufacturing capabilities are further supporting market expansion.',
    revenue: 211.4,
    forecast: 498.7,
    cagr: 11.2,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 115.2 },
      { year: 2019, value: 130.8 },
      { year: 2020, value: 148.1 },
      { year: 2021, value: 168.9 },
      { year: 2022, value: 192.3 },
      { year: 2023, value: 211.4 },
      { year: 2024, value: 235.0 },
      { year: 2025, value: 261.8 },
      { year: 2026, value: 291.5 },
      { year: 2027, value: 324.8 },
      { year: 2028, value: 361.6 },
      { year: 2029, value: 428.2 },
      { year: 2030, value: 498.7 },
    ],
    segments: ['Source Type', 'Production Type', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Roche', employees: '101,000+', hq: 'Basel, Switzerland', website: 'roche.com' },
      { name: 'AbbVie', employees: '50,000+', hq: 'North Chicago, USA', website: 'abbvie.com' },
      { name: 'Regeneron Pharmaceuticals', employees: '11,000+', hq: 'Tarrytown, USA', website: 'regeneron.com' },
      { name: 'Bristol-Myers Squibb', employees: '32,200+', hq: 'New York, USA', website: 'bms.com' },
      { name: 'Johnson & Johnson', employees: '152,000+', hq: 'New Brunswick, USA', website: 'jnj.com' },
      { name: 'Novartis', employees: '108,000+', hq: 'Basel, Switzerland', website: 'novartis.com' },
      { name: 'Amgen', employees: '24,000+', hq: 'Thousand Oaks, USA', website: 'amgen.com' },
      { name: 'Pfizer', employees: '83,000+', hq: 'New York, USA', website: 'pfizer.com' },
    ],
    highlights: [
      'Cancer treatment remains the largest application segment, accounting for 45% of total market revenue',
      'Humanized monoclonal antibodies dominate with 65% market share due to reduced immunogenicity',
      'North America leads the global market, contributing over 42% of total revenues in 2023',
      'Biosimilar development is gaining traction as key patents expire, creating cost-effective alternatives',
      'Asia Pacific is projected to be the fastest-growing region with a CAGR of 14.2% through 2030',
    ],
    relatedMarkets: [
      'North America Monoclonal Antibodies Market',
      'Europe Monoclonal Antibodies Market',
      'Asia Pacific Monoclonal Antibodies Market',
      'Bispecific Antibodies Market',
      'Antibody Drug Conjugates Market',
      'Biosimilars Market',
      'Cancer Immunotherapy Market',
      'Autoimmune Disease Treatment Market',
    ],
  },
  {
    slug: 'electric-vehicles',
    title: 'Electric Vehicles',
    industry: 'Automotive & Transportation',
    subIndustry: 'Electric Vehicles',
    region: 'global',
    description: 'The global electric vehicle market continues to accelerate as government mandates, falling battery costs, and expanding charging infrastructure drive mass adoption across passenger and commercial segments.',
    revenue: 388.1,
    forecast: 951.9,
    cagr: 13.7,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 102.3 },
      { year: 2019, value: 126.7 },
      { year: 2020, value: 143.9 },
      { year: 2021, value: 198.4 },
      { year: 2022, value: 302.1 },
      { year: 2023, value: 388.1 },
      { year: 2024, value: 445.2 },
      { year: 2025, value: 523.8 },
      { year: 2026, value: 621.0 },
      { year: 2027, value: 728.4 },
      { year: 2028, value: 810.3 },
      { year: 2029, value: 888.7 },
      { year: 2030, value: 951.9 },
    ],
    segments: ['Vehicle Type', 'Propulsion Type', 'Vehicle Class', 'End Use', 'Region'],
    companies: [
      { name: 'Tesla', employees: '127,855', hq: 'Austin, USA', website: 'tesla.com' },
      { name: 'BYD', employees: '570,000+', hq: 'Shenzhen, China', website: 'bydglobal.com' },
      { name: 'Volkswagen Group', employees: '684,000+', hq: 'Wolfsburg, Germany', website: 'volkswagen-group.com' },
      { name: 'General Motors', employees: '163,000', hq: 'Detroit, USA', website: 'gm.com' },
    ],
    highlights: [
      'Battery Electric Vehicles (BEVs) account for 71% of market share in 2023',
      'China dominates global EV adoption with 59% of new EV registrations',
      'Average EV battery cost has fallen 89% over the past decade to below $120/kWh',
      'Government incentives and stricter emission norms continue to accelerate adoption',
      'Charging infrastructure investment exceeded $15B globally in 2023',
    ],
    relatedMarkets: [
      'EV Battery Market',
      'EV Charging Infrastructure Market',
      'Autonomous Vehicle Market',
      'Battery Management System Market',
      'EV Motor Market',
    ],
  },
  {
    slug: 'solar-energy',
    title: 'Solar Energy',
    industry: 'Energy & Power',
    subIndustry: 'Solar Energy',
    region: 'global',
    description: 'The global solar energy market is experiencing unprecedented growth as declining photovoltaic panel costs and strong policy support make solar one of the cheapest forms of new electricity generation.',
    revenue: 223.8,
    forecast: 612.4,
    cagr: 15.5,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 89.4 },
      { year: 2019, value: 108.1 },
      { year: 2020, value: 121.7 },
      { year: 2021, value: 155.3 },
      { year: 2022, value: 194.2 },
      { year: 2023, value: 223.8 },
      { year: 2024, value: 263.5 },
      { year: 2025, value: 314.2 },
      { year: 2026, value: 378.9 },
      { year: 2027, value: 449.3 },
      { year: 2028, value: 512.8 },
      { year: 2029, value: 563.7 },
      { year: 2030, value: 612.4 },
    ],
    segments: ['Technology', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'LONGi Green Energy', employees: '80,000+', hq: 'Xi\'an, China', website: 'longi.com' },
      { name: 'First Solar', employees: '9,800+', hq: 'Tempe, USA', website: 'firstsolar.com' },
      { name: 'Sunrun', employees: '15,000+', hq: 'San Francisco, USA', website: 'sunrun.com' },
      { name: 'SunPower', employees: '5,000+', hq: 'San Jose, USA', website: 'sunpower.com' },
    ],
    highlights: [
      'Utility-scale solar installations represent 65% of total capacity additions globally',
      'Solar panel costs have declined 90% over the last decade, now below $0.20/W',
      'India and China combined account for 45% of new solar capacity additions',
      'Floating solar installations grew 30% YoY driven by land scarcity concerns',
    ],
    relatedMarkets: [
      'Solar Panel Market',
      'Solar Inverter Market',
      'Energy Storage Market',
      'Wind Energy Market',
      'Smart Grid Market',
    ],
  },
  {
    slug: 'digital-health',
    title: 'Digital Health',
    industry: 'Healthcare',
    subIndustry: 'Digital Health',
    region: 'global',
    description: 'The digital health market encompasses telemedicine, health IT, wearable devices, and AI-powered diagnostics. Increasing smartphone penetration and post-pandemic behavioral shifts are sustaining robust growth.',
    revenue: 211.0,
    forecast: 809.2,
    cagr: 21.2,
    yearStart: 2023,
    yearEnd: 2030,
    dataPoints: [
      { year: 2018, value: 86.4 },
      { year: 2019, value: 101.2 },
      { year: 2020, value: 152.8 },
      { year: 2021, value: 178.3 },
      { year: 2022, value: 196.4 },
      { year: 2023, value: 211.0 },
      { year: 2024, value: 268.4 },
      { year: 2025, value: 341.7 },
      { year: 2026, value: 428.3 },
      { year: 2027, value: 531.2 },
      { year: 2028, value: 634.9 },
      { year: 2029, value: 723.8 },
      { year: 2030, value: 809.2 },
    ],
    segments: ['Component', 'Application', 'End Use', 'Region'],
    companies: [
      { name: 'Teladoc Health', employees: '14,000+', hq: 'Purchase, USA', website: 'teladochealth.com' },
      { name: 'Philips Healthcare', employees: '77,000+', hq: 'Amsterdam, Netherlands', website: 'philips.com' },
      { name: 'Epic Systems', employees: '10,000+', hq: 'Verona, USA', website: 'epic.com' },
    ],
    highlights: [
      'Telehealth segment led the market with 28% revenue share in 2023',
      'AI-powered diagnostics are projected to grow at 28% CAGR through 2030',
      'Remote patient monitoring adoption doubled post-COVID-19',
    ],
    relatedMarkets: [
      'Telehealth Market',
      'Health IT Market',
      'Wearable Medical Devices Market',
      'AI in Healthcare Market',
    ],
  },
]

export const companies = [
  { slug: 'roche', name: 'Roche', sector: 'Healthcare', industry: 'Biotechnology', hq: 'Basel, Switzerland', employees: '101,000+', revenue: '$67.2B', operatingStatus: 'Active', website: 'roche.com', foundedYear: 1896, ipoStatus: 'Public', description: 'Roche is a global healthcare company that combines pharmaceuticals and diagnostics to pursue personalized medicine.' },
  { slug: 'abbvie', name: 'AbbVie', sector: 'Healthcare', industry: 'Pharmaceuticals', hq: 'North Chicago, USA', employees: '50,000+', revenue: '$56.2B', operatingStatus: 'Active', website: 'abbvie.com', foundedYear: 2013, ipoStatus: 'Public', description: 'AbbVie is a global biopharmaceutical company focused on immunology, oncology, neuroscience, and aesthetics.' },
  { slug: 'tesla', name: 'Tesla', sector: 'Technology', industry: 'Automotive & Transportation', hq: 'Austin, USA', employees: '127,855', revenue: '$96.8B', operatingStatus: 'Active', website: 'tesla.com', foundedYear: 2003, ipoStatus: 'Public', description: 'Tesla designs and manufactures electric vehicles, energy storage systems, and solar products.' },
  { slug: 'byd', name: 'BYD', sector: 'Technology', industry: 'Automotive & Transportation', hq: 'Shenzhen, China', employees: '570,000+', revenue: '$84.9B', operatingStatus: 'Active', website: 'bydglobal.com', foundedYear: 1995, ipoStatus: 'Public', description: 'BYD is a Chinese multinational conglomerate manufacturing automobiles, buses, electric bicycles, and batteries.' },
  { slug: 'medtronic', name: 'Medtronic', sector: 'Healthcare', industry: 'MedTech', hq: 'Dublin, Ireland', employees: '95,000+', revenue: '$32.0B', operatingStatus: 'Active', website: 'medtronic.com', foundedYear: 1949, ipoStatus: 'Public', description: 'Medtronic is a global leader in medical technology, services, and solutions serving physicians and healthcare systems.' },
  { slug: 'siemens-healthineers', name: 'Siemens Healthineers', sector: 'Healthcare', industry: 'MedTech', hq: 'Erlangen, Germany', employees: '69,500+', revenue: '$22.6B', operatingStatus: 'Active', website: 'siemens-healthineers.com', foundedYear: 1847, ipoStatus: 'Public', description: 'Siemens Healthineers is a leading medical technology company focused on diagnostic imaging and laboratory diagnostics.' },
  { slug: 'longi-green-energy', name: 'LONGi Green Energy', sector: 'Energy', industry: 'Energy & Power', hq: 'Xi\'an, China', employees: '80,000+', revenue: '$18.9B', operatingStatus: 'Active', website: 'longi.com', foundedYear: 2000, ipoStatus: 'Public', description: 'LONGi is the world\'s largest solar technology company, specializing in monocrystalline silicon photovoltaic products.' },
  { slug: 'pfizer', name: 'Pfizer', sector: 'Healthcare', industry: 'Pharmaceuticals', hq: 'New York, USA', employees: '83,000+', revenue: '$85.0B', operatingStatus: 'Active', website: 'pfizer.com', foundedYear: 1849, ipoStatus: 'Public', description: 'Pfizer is a leading global pharmaceutical company developing medicines, vaccines, and consumer healthcare products.' },
  { slug: 'teladoc-health', name: 'Teladoc Health', sector: 'Healthcare', industry: 'Healthcare', hq: 'Purchase, USA', employees: '14,000+', revenue: '$2.6B', operatingStatus: 'Active', website: 'teladochealth.com', foundedYear: 2002, ipoStatus: 'Public', description: 'Teladoc Health is a global leader in virtual care, providing telehealth services to individuals and health plans.' },
  { slug: 'novartis', name: 'Novartis', sector: 'Healthcare', industry: 'Pharmaceuticals', hq: 'Basel, Switzerland', employees: '108,000+', revenue: '$45.4B', operatingStatus: 'Active', website: 'novartis.com', foundedYear: 1996, ipoStatus: 'Public', description: 'Novartis is a global healthcare company dedicated to reimagining medicine to improve and extend people\'s lives.' },
]

export const testimonials = [
  {
    company: 'GE Healthcare',
    name: 'Sarah Mitchell',
    title: 'VP Strategy & Market Intelligence',
    quote: 'Horizon Intelligence has transformed how we approach market research. The depth of data and AI-powered insights have cut our research time by 60% while improving decision quality.',
    avatar: 'SM',
    logo: 'GE',
  },
  {
    company: 'KPMG Netherlands',
    name: 'Dirk van der Berg',
    title: 'Director of Life Sciences Advisory',
    quote: 'The breadth of coverage is unmatched. From granular statistics to executive summaries, Horizon gives our consulting teams exactly what they need to advise clients confidently.',
    avatar: 'DB',
    logo: 'KPMG',
  },
  {
    company: 'NICCA USA',
    name: 'James Holloway',
    title: 'Head of Business Development',
    quote: 'The market segmentation data and company profiles helped us identify three acquisition targets we would have missed otherwise. Exceptional ROI on our subscription.',
    avatar: 'JH',
    logo: 'NICCA',
  },
]

export const partnerLogos = [
  'Medtronic', 'GE Healthcare', 'Siemens', 'Johnson & Johnson',
  'Accenture', 'Google', 'Deloitte', 'KPMG', 'Pfizer', 'Novartis',
  'Merck', 'AstraZeneca', 'Goldman Sachs', 'McKinsey', 'BCG',
]

export const pricingPlans = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: null,
    users: 1,
    cta: 'Sign up free',
    description: 'Perfect for exploring market data',
    features: [
      { label: 'Overview statistics (limited)', included: true },
      { label: 'Basic search access', included: true },
      { label: '3 AI queries/month', included: true },
      { label: 'Company directory (basic)', included: true },
      { label: 'Full statistics access', included: false },
      { label: 'Dashboard & charts', included: false },
      { label: 'White papers', included: false },
      { label: 'CSV/XLS exports', included: false },
      { label: 'Full reports', included: false },
    ],
    highlighted: false,
    badge: null,
  },
  {
    id: 'basic',
    name: 'Basic',
    price: 195,
    period: 'month',
    users: 1,
    cta: 'Buy Now',
    description: 'For individual analysts and researchers',
    features: [
      { label: 'Full statistics access (500 rows)', included: true },
      { label: 'Dashboard & interactive charts', included: true },
      { label: '20 AI queries/month', included: true },
      { label: 'CSV & XLS exports', included: true },
      { label: '1 full report/year included', included: true },
      { label: 'Company directory (full)', included: true },
      { label: 'White papers', included: false },
      { label: 'PowerPoint export', included: false },
      { label: 'Priority support', included: false },
    ],
    highlighted: false,
    badge: null,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 495,
    period: 'month',
    users: 2,
    cta: 'Buy Now',
    description: 'Full access for power users',
    features: [
      { label: 'Full statistics access (unlimited)', included: true },
      { label: 'Dashboard & interactive charts', included: true },
      { label: 'Unlimited AI queries', included: true },
      { label: 'All export formats + PowerPoint', included: true },
      { label: '25 full reports/year included', included: true },
      { label: 'White papers & thought leadership', included: true },
      { label: 'Priority analyst support', included: true },
      { label: 'API access (beta)', included: true },
      { label: 'Custom alerts & notifications', included: true },
    ],
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 1995,
    period: 'month',
    users: 10,
    cta: 'Contact Sales',
    description: 'Custom solutions for large teams',
    features: [
      { label: 'Everything in Premium', included: true },
      { label: 'Custom data integrations', included: true },
      { label: 'Dedicated account manager', included: true },
      { label: 'Custom report commissioning', included: true },
      { label: 'SLA & enterprise security', included: true },
      { label: 'Team management dashboard', included: true },
      { label: 'Unlimited users', included: true },
      { label: 'White-label options', included: true },
      { label: 'Custom pricing available', included: true },
    ],
    highlighted: false,
    badge: null,
  },
]

export const stats = [
  { value: 30000, suffix: '+', label: 'Global & Regional Reports', prefix: '' },
  { value: 120000, suffix: '+', label: 'Country Reports', prefix: '' },
  { value: 1200000, suffix: '+', label: 'Market Statistics', prefix: '' },
  { value: 200000, suffix: '+', label: 'Company Profiles', prefix: '' },
]
