export const industries = [
  { id: 'aerospace', name: 'Aerospace & Defence', subIndustries: ['Commercial Aviation', 'Defense Systems', 'Space Technology', 'Drones & UAVs', 'Satellites'] },
  { id: 'animal-health', name: 'Animal Health', subIndustries: ['Vaccines', 'Diagnostics', 'Feed Additives', 'Companion Animal', 'Livestock'] },
  { id: 'automotive', name: 'Automotive & Transportation', subIndustries: ['Electric Vehicles', 'Autonomous Vehicles', 'Fleet Management', 'Telematics', 'Automotive Parts'] },
  { id: 'biotech', name: 'Biotechnology', subIndustries: ['Monoclonal Antibodies', 'Gene Therapy', 'Cell Therapy', 'Bioinformatics', 'Synthetic Biology', 'Bioprocessing'] },
  { id: 'bulk-chemicals', name: 'Bulk Chemicals', subIndustries: ['Industrial Gases', 'Petrochemicals', 'Fertilizers', 'Chlor-Alkali', 'Acids & Bases'] },
  { id: 'clinical-diagnostics', name: 'Clinical Diagnostics', subIndustries: ['Molecular Diagnostics', 'Point-of-Care Testing', 'Immunoassays', 'Histology', 'Flow Cytometry'] },
  { id: 'consumer-goods', name: 'Consumer Goods', subIndustries: ['Personal Care', 'Home Care', 'Beauty & Cosmetics', 'Apparel', 'Electronics'] },
  { id: 'consumer-services', name: 'Consumer Services', subIndustries: ['E-commerce', 'Streaming', 'Travel & Tourism', 'Food Delivery', 'EdTech'] },
  { id: 'energy', name: 'Energy & Power', subIndustries: ['Solar Energy', 'Wind Energy', 'Energy Storage', 'Oil & Gas', 'Smart Grid'] },
  { id: 'financial-services', name: 'Financial Services', subIndustries: ['Fintech', 'Banking', 'Insurance', 'Asset Management', 'Payments'] },
  { id: 'food-beverages', name: 'Food Beverages & Tobacco', subIndustries: ['Functional Food', 'Plant-Based', 'Beverages', 'Dairy', 'Tobacco Alternatives'] },
  { id: 'healthcare', name: 'Healthcare', subIndustries: ['Digital Health', 'Hospital Management', 'Telehealth', 'Wearables', 'Health IT'] },
  { id: 'materials', name: 'Materials', subIndustries: ['Advanced Materials', 'Composites', 'Ceramics', 'Coatings', 'Adhesives'] },
  { id: 'medtech', name: 'MedTech', subIndustries: ['Surgical Robotics', 'Imaging Systems', 'Implants', 'Wound Care', 'Orthopedics'] },
  { id: 'metals-mining', name: 'Metals & Mining', subIndustries: ['Rare Earth Elements', 'Steel', 'Aluminum', 'Copper', 'Lithium'] },
  { id: 'nutrition', name: 'Nutrition', subIndustries: ['Sports Nutrition', 'Dietary Supplements', 'Infant Nutrition', 'Clinical Nutrition', 'Probiotics'] },
  { id: 'packaging', name: 'Packaging', subIndustries: ['Flexible Packaging', 'Rigid Plastics', 'Sustainable Packaging', 'Smart Packaging', 'Labels'] },
  { id: 'pharma', name: 'Pharmaceuticals', subIndustries: ['Oncology', 'CNS', 'Cardiovascular', 'Generic Drugs', 'Contract Manufacturing'] },
  { id: 'plastics', name: 'Plastics', subIndustries: ['Engineering Plastics', 'Bio-Based Plastics', 'Recycled Plastics', 'Films', 'Foams'] },
  { id: 'semiconductor', name: 'Semiconductor', subIndustries: ['Memory Chips', 'Logic Chips', 'Power Semiconductors', 'Sensors', 'Photonics'] },
  { id: 'sexual-health', name: 'Sexual Health', subIndustries: ['Contraceptives', 'STI Testing', 'Fertility', 'ED Treatment', 'Sex Wellness'] },
  { id: 'specialty-chemicals', name: 'Specialty Chemicals', subIndustries: ['Electronic Chemicals', 'Agrochemicals', 'Construction Chemicals', 'Water Treatment', 'Surfactants'] },
  { id: 'telecom', name: 'Telecom & Technology', subIndustries: ['5G', 'Cloud Computing', 'Cybersecurity', 'IoT', 'AI & ML', 'Quantum Computing'] },
]

export const companies = [
  { slug: 'roche', name: 'Roche', sector: 'Healthcare', industry: 'Biotechnology', hq: 'Basel, Switzerland', employees: '101,000+', revenue: '$67.2B', operatingStatus: 'Active', website: 'roche.com', foundedYear: 1896, ipoStatus: 'Public', description: 'Roche is a global healthcare company that combines pharmaceuticals and diagnostics to pursue personalized medicine.' },
  { slug: 'abbvie', name: 'AbbVie', sector: 'Healthcare', industry: 'Pharmaceuticals', hq: 'North Chicago, USA', employees: '50,000+', revenue: '$56.2B', operatingStatus: 'Active', website: 'abbvie.com', foundedYear: 2013, ipoStatus: 'Public', description: 'AbbVie is a global biopharmaceutical company focused on immunology, oncology, neuroscience, and aesthetics.' },
  { slug: 'tesla', name: 'Tesla', sector: 'Technology', industry: 'Automotive & Transportation', hq: 'Austin, USA', employees: '127,855', revenue: '$96.8B', operatingStatus: 'Active', website: 'tesla.com', foundedYear: 2003, ipoStatus: 'Public', description: 'Tesla designs and manufactures electric vehicles, energy storage systems, and solar products.' },
  { slug: 'byd', name: 'BYD', sector: 'Technology', industry: 'Automotive & Transportation', hq: 'Shenzhen, China', employees: '570,000+', revenue: '$84.9B', operatingStatus: 'Active', website: 'bydglobal.com', foundedYear: 1995, ipoStatus: 'Public', description: 'BYD is a Chinese multinational conglomerate manufacturing automobiles, buses, electric bicycles, and batteries.' },
  { slug: 'medtronic', name: 'Medtronic', sector: 'Healthcare', industry: 'MedTech', hq: 'Dublin, Ireland', employees: '95,000+', revenue: '$32.0B', operatingStatus: 'Active', website: 'medtronic.com', foundedYear: 1949, ipoStatus: 'Public', description: 'Medtronic is a global leader in medical technology, services, and solutions serving physicians and healthcare systems.' },
  { slug: 'siemens-healthineers', name: 'Siemens Healthineers', sector: 'Healthcare', industry: 'MedTech', hq: 'Erlangen, Germany', employees: '69,500+', revenue: '$22.6B', operatingStatus: 'Active', website: 'siemens-healthineers.com', foundedYear: 1847, ipoStatus: 'Public', description: 'Siemens Healthineers is a leading medical technology company focused on diagnostic imaging and laboratory diagnostics.' },
  { slug: 'longi-green-energy', name: 'LONGi Green Energy', sector: 'Energy', industry: 'Energy & Power', hq: 'Xi\'an, China', employees: '80,000+', revenue: '$18.9B', operatingStatus: 'Active', website: 'longi.com', foundedYear: 2000, ipoStatus: 'Public', description: 'LONGi is the world\'s largest solar technology company, specializing in monocrystalline silicon photovoltaic products.' },
  { slug: 'pfizer', name: 'Pfizer', sector: 'Healthcare', industry: 'Pharmaceuticals', hq: 'New York, USA', employees: '83,000+', revenue: '$85.0B', operatingStatus: 'Active', website: 'pfizer.com', foundedYear: 1849, ipoStatus: 'Public', description: 'Pfizer is a leading global pharmaceutical company developing medicines, vaccines, and consumer healthcare products.' },
  { slug: 'teladoc-health', name: 'Teladoc Health', sector: 'Healthcare', industry: 'Healthcare', hq: 'Purchase, USA', employees: '14,000+', revenue: '$2.6B', operatingStatus: 'Active', website: 'teladochealth.com', foundedYear: 2002, ipoStatus: 'Public', description: 'Teladoc Health is a global leader in virtual care, providing telehealth services to individuals and health plans.' },
  { slug: 'novartis', name: 'Novartis', sector: 'Healthcare', industry: 'Pharmaceuticals', hq: 'Basel, Switzerland', employees: '108,000+', revenue: '$45.4B', operatingStatus: 'Active', website: 'novartis.com', foundedYear: 1996, ipoStatus: 'Public', description: 'Novartis is a global healthcare company dedicated to reimagining medicine to improve and extend people\'s lives.' },
]

export const testimonials = [
  {
    company: 'GE Healthcare',
    name: 'Sarah Mitchell',
    title: 'VP Strategy & Market Intelligence',
    quote: 'Curator Intelligence has transformed how we approach market research. The depth of data and AI-powered insights have cut our research time by 60% while improving decision quality.',
    avatar: 'SM',
    logo: 'GE',
  },
  {
    company: 'KPMG Netherlands',
    name: 'Dirk van der Berg',
    title: 'Director of Life Sciences Advisory',
    quote: 'The breadth of coverage is unmatched. From granular statistics to executive summaries, Curator gives our consulting teams exactly what they need to advise clients confidently.',
    avatar: 'DB',
    logo: 'KPMG',
  },
  {
    company: 'NICCA USA',
    name: 'James Holloway',
    title: 'Head of Business Development',
    quote: 'The market segmentation data and company profiles helped us identify three acquisition targets we would have missed otherwise. Exceptional ROI on our subscription.',
    avatar: 'JH',
    logo: 'NICCA',
  },
]

export const partnerLogos = [
  { name: 'Medtronic',            domain: 'medtronic.com',            color: '#00a3e0' },
  { name: 'GE Healthcare',        domain: 'gehealthcare.com',         color: '#0033a0' },
  { name: 'Siemens Healthineers', domain: 'siemens-healthineers.com', color: '#009999' },
  { name: 'Johnson & Johnson',    domain: 'jnj.com',                  color: '#d51f2e' },
  { name: 'Accenture',            domain: 'accenture.com',            color: '#a100ff' },
  { name: 'Google',               domain: 'google.com',               color: '#4285f4' },
  { name: 'Deloitte',             domain: 'deloitte.com',             color: '#86bc25' },
  { name: 'KPMG',                 domain: 'kpmg.com',                 color: '#00338d' },
  { name: 'Pfizer',               domain: 'pfizer.com',               color: '#0093c8' },
  { name: 'Novartis',             domain: 'novartis.com',             color: '#e1261c' },
  { name: 'Merck',                domain: 'merck.com',                color: '#009fdf' },
  { name: 'AstraZeneca',          domain: 'astrazeneca.com',          color: '#830051' },
  { name: 'Goldman Sachs',        domain: 'goldmansachs.com',         color: '#1a3c5e' },
  { name: 'McKinsey & Company',   domain: 'mckinsey.com',             color: '#002d5c' },
  { name: 'BCG',                  domain: 'bcg.com',                  color: '#00823e' },
]

export const pricingPlans = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: null,
    users: 1,
    cta: 'Sign up free',
    description: 'Perfect for exploring market data',
    features: [
      { label: 'Overview statistics (limited)', included: true },
      { label: 'Basic search access', included: true },
      { label: '3 AI queries/month', included: true },
      { label: 'Company directory (basic)', included: true },
      { label: 'Full statistics access', included: false },
      { label: 'Dashboard & charts', included: false },
      { label: 'White papers', included: false },
      { label: 'CSV/XLS exports', included: false },
      { label: 'Full reports', included: false },
    ],
    highlighted: false,
    badge: null,
  },
  {
    id: 'basic',
    name: 'Basic',
    price: 195,
    period: 'month',
    users: 1,
    cta: 'Buy Now',
    description: 'For individual analysts and researchers',
    features: [
      { label: 'Full statistics access (500 rows)', included: true },
      { label: 'Dashboard & interactive charts', included: true },
      { label: '20 AI queries/month', included: true },
      { label: 'CSV & XLS exports', included: true },
      { label: '1 full report/year included', included: true },
      { label: 'Company directory (full)', included: true },
      { label: 'White papers', included: false },
      { label: 'PowerPoint export', included: false },
      { label: 'Priority support', included: false },
    ],
    highlighted: false,
    badge: null,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 495,
    period: 'month',
    users: 2,
    cta: 'Buy Now',
    description: 'Full access for power users',
    features: [
      { label: 'Full statistics access (unlimited)', included: true },
      { label: 'Dashboard & interactive charts', included: true },
      { label: 'Unlimited AI queries', included: true },
      { label: 'All export formats + PowerPoint', included: true },
      { label: '25 full reports/year included', included: true },
      { label: 'White papers & thought leadership', included: true },
      { label: 'Priority analyst support', included: true },
      { label: 'API access (beta)', included: true },
      { label: 'Custom alerts & notifications', included: true },
    ],
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 1995,
    period: 'month',
    users: 10,
    cta: 'Contact Sales',
    description: 'Custom solutions for large teams',
    features: [
      { label: 'Everything in Premium', included: true },
      { label: 'Custom data integrations', included: true },
      { label: 'Dedicated account manager', included: true },
      { label: 'Custom report commissioning', included: true },
      { label: 'SLA & enterprise security', included: true },
      { label: 'Team management dashboard', included: true },
      { label: 'Unlimited users', included: true },
      { label: 'White-label options', included: true },
      { label: 'Custom pricing available', included: true },
    ],
    highlighted: false,
    badge: null,
  },
]

export const stats = [
  { value: 30000, suffix: '+', label: 'Global & Regional Reports', prefix: '' },
  { value: 120000, suffix: '+', label: 'Country Reports', prefix: '' },
  { value: 1200000, suffix: '+', label: 'Market Statistics', prefix: '' },
  { value: 200000, suffix: '+', label: 'Company Profiles', prefix: '' },
]
