// Typed accessors for the WP-derived report data.
// Generated by scripts/extract-wp-reports.mjs + scripts/build-reports-catalog.mjs.

import type { Market } from '@/types'
import catalogJson from './reports.catalog.json'
import summariesJson from './reports.summaries.json'
export { wpIndustries, wpIndustriesAsIndustry, type WpIndustry } from './industries'

export interface WpReportSummary {
  id: number
  slug: string
  title: string
  excerpt: string
  industry: string
  categories: string[]
  tags: string[]
  regions: string[]
  publishedDate: string
  pages: string | null
  cagr: number | null
  baseYear: number | null
  yearStart: number | null
  yearEnd: number | null
  studyPeriod: string | null
  code: string | null
  prices: {
    single: number | null
    team: number | null
    enterprise: number | null
    dataPack: number | null
  }
  modified: string
}

export interface WpReportFull extends WpReportSummary {
  description: string
  segmentation: string
  tableOfContents: string
  methodology: string
  keyPlayers: string
  faqs: { q: string; a: string }[]
  seo: { title: string; description: string }
}

export const wpCatalog = catalogJson as WpReportSummary[]

const summariesMap = new Map(
  (summariesJson as { slug: string; summary: string }[]).map((s) => [s.slug, s.summary]),
)
export const getReportAISummary = (slug: string): string | undefined => summariesMap.get(slug)

const slugToReport = new Map(wpCatalog.map((r) => [r.slug, r]))
export const getReportSummary = (slug: string) => slugToReport.get(slug)

// Adapter: WP report → existing Market shape so the current UI keeps working.
// Fields the WP data doesn't carry (dataPoints, revenue, forecast, companies,
// highlights, relatedMarkets) are stubbed; the outlook page already tolerates
// empty arrays.
export function wpToMarket(r: WpReportSummary): Market {
  const yearStart = r.yearStart ?? r.baseYear ?? 2024
  const yearEnd = r.yearEnd ?? yearStart + 6
  return {
    slug: r.slug,
    title: r.title,
    industry: r.industry,
    subIndustry: r.categories.find((c) => c !== r.industry) || r.industry,
    region: r.regions[0] || 'Global',
    description: r.excerpt,
    revenue: 0,
    forecast: 0,
    cagr: r.cagr ?? 0,
    yearStart,
    yearEnd,
    dataPoints: [],
    segments: r.tags.slice(0, 6),
    companies: [],
    highlights: [],
    relatedMarkets: [],
    type: 'Report',
  }
}

export const wpMarkets: Market[] = wpCatalog.map(wpToMarket)
